### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by JackChenLucky** [hs-web/hsweb-framework#10]
我想使用你这套开源的项目搭建基础框架。但是发现项目引用太多。很难运行起来。各种自家的项目。非常麻烦。既然是后台管理基础框架。为什么不把你的自家项目需要的放在hsweb-framework下，大不了新增一个module。现在很痛苦弄起来。希望能够交流。

**Comment by zhou-hao** [comment]
因为其他的也是独立的功能，并不局限这里用。目前都发布到maven私服了，你可以参考hsweb-demo的用法。感谢反馈。

**Comment by zhou-hao** [comment]
https://github.com/hs-web/hsweb-demo
