### ISSUE TITLE
配置元数据时报错

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#105]
1. 问题描述:

使用`spring-boot-configuration-processor`配置元数据时报错

2. 复现步骤:
- 引入`spring-boot-configuration-processor`依赖
- 执行`mvn install`
3. 日志内容:
> Duplicate `@ConfigurationProperties` definition for prefix 'hsweb.oauth2.file-server'
https://github.com/hs-web/hsweb-framework/blob/e8dc76c06bf1572a09174e7543a587f0c86cf69c/hsweb-system/hsweb-system-file/hsweb-system-file-oauth2/src/main/java/org/hswebframework/web/service/file/oauth2/OAuth2FileAutoConfiguration.java#L17-L27

springboot官方issue spring-projects/spring-boot#6781

**Comment by zhou-hao** [comment]
暂不做处理。
