### ISSUE TITLE
lombok导入

### ISSUE THREAD

**Issue by lsr90518** [hs-web/hsweb-framework#11]
看到项目中并没有使用lombok。是否考虑使用？为了减少代码量和增强可读性。

**Comment by lsr90518** [comment]
特别是po
https://github.com/hs-web/hsweb-framework/blob/master/hsweb-web-bean/src/main/java/org/hsweb/web/bean/po/role/Role.java

以及logger
https://github.com/hs-web/hsweb-framework/blob/master/hsweb-web-controller/src/main/java/org/hsweb/web/controller/GenericController.java#L44

**Comment by zhou-hao** [comment]
感谢反馈，这个后期可以考虑。以前都是代码生成器生成的，所以没有管这些。
