### ISSUE TITLE
[BUG]用户配置管理->获取当前用户的配置接口响应结果有问题

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#112]
### BUG 说明
获取当前用户的配置的接口一直返回空数据，但是**Demo中代码生成器**有俩处会获取保存的用户配置进行初始化
- [1](https://github.com/hs-web/hsweb3-demo/blob/b9e0920c346b93a245e2ccb648d3fda2c83ce172/hsweb-ui/admin/code-generator/index.js#L34-L43)
- [2](https://github.com/hs-web/hsweb3-demo/blob/b9e0920c346b93a245e2ccb648d3fda2c83ce172/hsweb-ui/admin/code-generator/index.js#L179-L189)
 
### BUG 定位
https://github.com/hs-web/hsweb-framework/blob/e88e8efc636c3a9f4b65a47f2775500bdd4796b5/hsweb-system/hsweb-system-authorization/hsweb-system-authorization-web/src/main/java/org/hswebframework/web/authorization/controller/UserSettingController.java#L41-L44
这里的逻辑是不是也有问题呀？:question:

### 截图说明
![image](https://user-images.githubusercontent.com/31472350/52705472-f529ea00-2fbd-11e9-878c-24e6f91b9737.png)

**Comment by zhou-hao** [comment]
感谢提交,此bug比较低级。

影响版本: 3.0.4-3.0.6 
将在3.0.7修复
