### ISSUE TITLE
[BUG]跨域配置存在问题

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#113]
### BUG 说明
开启跨域配置，自定义的`allowed-methods`不起作用

### 复现步骤
 spring-projects/spring-boot#15796

**Comment by zhou-hao** [comment]
使用配置: hsweb.cors 试试没
```java
hsweb:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allowed-origins: "*"
      enable: true
```

**Comment by JiaRG** [comment]
这种配置是可以的

**Comment by zhou-hao** [comment]
https://github.com/hs-web/hsweb-framework/blob/f7815fb4eac90de89a0684398e03e0e55940c95b/hsweb-starter/hsweb-spring-boot-starter/src/main/java/org/hswebframework/web/starter/CorsAutoConfiguration.java#L17-L33

**Comment by JiaRG** [comment]
@zhou-hao springboot那个issue就是你这种的配置方式，它只支持`*`，如果自定义的话就有问题了

**Comment by zhou-hao** [comment]
使用`hsweb.cors` 时，也只支持* ?

**Comment by JiaRG** [comment]
😓是的，springboot那个issue跟你这的区别就是没有`hsweb`这个词，我在QQ群里说过这个问题

**Comment by zhou-hao** [comment]
好的，有时间解决解决
