### ISSUE TITLE
[BUG]版本更新条件判断错误及hsweb-starter.js测试打印信息错误

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#115]
### BUG 说明
https://github.com/hs-web/hsweb-framework/blob/34effefdcc4b766fe59e6c6c95452e73035d591b/hsweb-starter/hsweb-spring-boot-starter/src/main/java/org/hswebframework/web/starter/init/simple/SimpleDependencyInstaller.java#L55-L62
https://github.com/hs-web/hsweb-framework/blob/34effefdcc4b766fe59e6c6c95452e73035d591b/hsweb-starter/hsweb-spring-boot-starter/src/test/resources/hsweb-starter.js#L28-L48

**Comment by zhou-hao** [comment]
这看上去像闭着眼睛写的bug！！！
