### ISSUE TITLE
  将表单生成模块单独弄出来  mybatis  报错 

### ISSUE THREAD

**Issue by Seriels** [hs-web/hsweb-framework#118]
# BUG 说明
简要说明bug情况

# 运行环境
java: 11
maven: 3.5.0
hsweb: 最新
 
# 复现步骤
  将表单生成模块单独弄出来  使用  mybatis  报错    DynamicFormService   类的  deploy(id);出错 

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: Error instantiating interface org.hswebframework.web.entity.form.DynamicFormEntity with invalid types () or values (). Cause: java.lang.NoSuchMethodException: org.hswebframework.web.entity.form.DynamicFormEntity.<init>()

关键  报错位置  at org.hswebframework.web.service.form.simple.SimpleDynamicFormService.selectByPk(SimpleDynamicFormService.java:196) ~[classes/:na]
	at org.hswebframework.web.service.form.simple.SimpleDynamicFormService.deploy(SimpleDynamicFormService.java:411) ~[classes/:na]
# 期望结果
成功 发布

# 截图说明

**Comment by zhou-hao** [comment]
检查一下是否引入了 `hsweb-spring-boot-starter`

**Comment by Seriels** [comment]
> 检查一下是否引入了 `hsweb-spring-boot-starter`

可以使用生成表单方法 但是不能  使用deploy

**Comment by zhou-hao** [comment]
这个应该是无法映射实体类。 可以试试引入`hsweb-spring-boot-starter` 。

**Comment by Seriels** [comment]
> 这个应该是无法映射实体类。 可以试试引入`hsweb-spring-boot-starter` 。

已使用此办法解决  非常感谢
