### ISSUE TITLE
[疑问]

### ISSUE THREAD

**Issue by kostark** [hs-web/hsweb-framework#121]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
基础服务中有实现缓存的扩展类：在抽象类的方法上用来 `@Cache*` 注解，而在子类上标注 `@CacheConfig` 的写法。。
但是据我了解和测试的情况来说，。。。

https://stackoverflow.com/questions/36977643/spring-cache-not-working-for-abstract-classes

**Comment by zhou-hao** [comment]
ok 有时间优化优化
