### ISSUE TITLE
ORM选择JPA mybatis[疑问]

### ISSUE THREAD

**Issue by MeDeity** [hs-web/hsweb-framework#126]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
这个issue可能没什么价值，初步涉及后端，我有个小疑惑，为什么很多国内的开源项目倾向于使用mybatis,而不是使用JPA. 因为mybatis更灵活吗?比如这个项目,谢谢

**Comment by zhou-hao** [comment]
我觉得历史原因为主。 那时候hibernate用起来比较蛋疼。mybatis一开始流行起来了，培训机构ssm一把梭。于是。。。 本项目采用mybatis没有特殊的原因。因为自己熟悉，所以一直用呗。

**Comment by MeDeity** [comment]
谢谢解惑.我也在网上搜索了一些信息
[知乎:MyBatis为什么在国内相当流行?](https://www.zhihu.com/question/50729231)
