### ISSUE TITLE
[需求]

### ISSUE THREAD

**Issue by shansheng** [hs-web/hsweb-framework#127]
# 场景
是否考虑添加一下工作流模块。我看hsweb-platform这个里面有个工作流建模，感觉是不是半途而废了
# 需求说明

**Comment by zhou-hao** [comment]
有工作流。 http://demo3.hsweb.me test test  或者本地运行: https://github.com/hs-web/hsweb3-demo  不过暂时没有做更深入的集成和前端页面。

**Comment by shansheng** [comment]
我只看了miniui的版本，因为我们正在用这个开发。不好意思。这个最新版确实看到了。谢谢
