### ISSUE TITLE
[疑问] 最好提供下软件的截图界面

### ISSUE THREAD

**Issue by xiaoyongzeng** [hs-web/hsweb-framework#129]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明

**Comment by zhou-hao** [comment]
hsweb-framework 不提供任何前端实现。目前只有一个前端demo。 http://demo3.hsweb.me  账号test密码test ，源代码：  https://github.com/hs-web/hsweb3-demo
