### ISSUE TITLE
hsweb-web-oauth2 这个模块,如何使用，谢谢

### ISSUE THREAD

**Issue by kleen** [hs-web/hsweb-framework#13]
hsweb-web-oauth2 这个模块,如何使用，谢谢

**Comment by zhou-hao** [comment]
目前只支持 简单的client_credentials方式。 参照 [文档](https://github.com/hs-web/hsweb-framework/tree/master/hsweb-web-oauth2) 和 [demo](https://github.com/hs-web/hsweb-demo)
