### ISSUE TITLE
多表级联查询没法做到分页[需求]

### ISSUE THREAD

**Issue by hl0071** [hs-web/hsweb-framework#133]
# 场景
比如列表显示一些带关联的表时，返回的结果不带分页信息，一种办法是修改JS来分页
# 需求说明
但是感觉还是用程序分页比较好，控制比较好，自己扩展的级联查询，被PagerInterceptor拦截，hsweb框架返回的是getactivetable的字段，sql join 不能处理多个表格查询。。。

**Comment by zhou-hao** [comment]
关联查询 可以参照 : https://github.com/hs-web/hsweb-framework/tree/master/hsweb-commons/hsweb-commons-dao/hsweb-commons-dao-mybatis#%E4%BD%BF%E7%94%A8%E9%80%9A%E7%94%A8mapper-xml

大概就是:
```xml
<!--另外一个resultMap,用于演示表关联-->
    <resultMap id="TestNestResultMap" type="org.hswebframework.web.dao.crud.TestEntity">
        <id property="id" column="id" javaType="Long" jdbcType="INTEGER"/>
        <!--jpa目前不支持表关联的解析,所以要在这里定义另外一个关联实体的全部信息,其中,column=关联表别名.列名-->
        <result property="nest.name" column="nest_table.name" javaType="String" jdbcType="VARCHAR"/>
    </resultMap>

     <!--表关联的查询-->
    <select id="queryNest" parameterType="org.hswebframework.web.commons.entity.Entity" resultMap="TestNestResultMap">
        <bind name="tableName" value="'h_test'"/>
        <bind name="resultMapId" value="'TestNestResultMap'"/>
        select
        <include refid="BasicMapper.buildSelectField"/>
        from h_test <!--注意h_nest_table的别名:nest_table-->
        left join h_nest_table nest_table on nest_table.id=h_test.id
        <where>
            <include refid="BasicMapper.buildWhere"/>
        </where>
        <include refid="BasicMapper.buildSortField"/>
    </select>

    <select id="countNest" parameterType="org.hswebframework.web.commons.entity.Entity" resultType="int">
        <include refid="config"/>
        select
        count(1)
        from h_test
        left join h_nest_table nest_table on nest_table.id=h_test.id
        <where>
            <include refid="BasicMapper.buildWhere"/>
        </where>
    </select>

```

**Comment by hl0071** [comment]
OK了，我在service层用代码，循环查询，实现了表的关联，谢谢，又学到一个新方法

**Comment by zhou-hao** [comment]
嗯，一对多，多对多都时候，可以用这种方式逻辑关联。  但是不推荐循环查询，可以使用2次查询，然后分组关联。

**Comment by hl0071** [comment]
`<select id="query" parameterType="org.hswebframework.web.commons.entity.Entity"
            resultMap="OrganizationSimpleResultMap">
        ${@cotron.admin.web.mybatis.builder.CustomSqlBuilder@current().SetPageInfo(#this['_parameter'])}
        <bind name="tableName" value="'pptr_subnet'"></bind>
        <bind name="resultMapId" value="'SubNetOrgResultMap'"></bind>
        select
        <include refid="BasicMapper.buildSelectField"></include>
        from pptr_subnet s left join s_organization o on s.organization=o.u_id
        <where>
            <include refid="BasicMapper.buildWhere"></include>
        </where>
        <include refid="BasicMapper.buildSortField"></include>
    </select>`
弄了一个星期，自己设置分页页码，然后自己buildsql语句，笑哭，感觉自己弄得好别扭，不过对框架有新的认识

**Comment by zhou-hao** [comment]
还有一种玩法，针对通用动态条件对。 
https://github.com/hs-web/hsweb-framework/tree/master/hsweb-system/hsweb-system-organizational#sql%E6%9D%A1%E4%BB%B6

**Comment by hl0071** [comment]
你之前那种玩法，会不会出现分页错误？毕竟查的时候要调用count，mapper里面count用的另一个resultmapper，不知道状态会不会冲突

**Comment by zhou-hao** [comment]
这种查询肯定分页也到单独写一个对应对

**Comment by hl0071** [comment]
分页设置静态Pager类就行了吧?PagerInterceptor会自动获取并设置SQL语句

**Comment by zhou-hao** [comment]
分页会，但是count 要单独写

**Comment by hl0071** [comment]
不支持association，感觉好别扭

**Comment by zhou-hao** [comment]
在3.0.9 开始支持了。也支持jpa注解方式来定义映射，可以看一下commit https://github.com/hs-web/hsweb-framework/commit/f5a729c6b1772d57a6baf63a82a9ed60d3a2a057

**Comment by hl0071** [comment]
三个以上表级联，就乱报错。。。

**Comment by zhou-hao** [comment]
怎么关联的

**Comment by hl0071** [comment]
`<select id="queryUnion" parameterType="org.hswebframework.web.commons.entity.Entity"
            resultMap="HardwareAssetResultMap">
        <include refid="unionConfig"></include>
        ${@cotron.admin.web.mybatis.builder.CustomSqlBuilder@current().SetPageInfo(#this['_parameter'])}
        select
        <include refid="BasicMapper.buildSelectField"></include>
        from pptr_hardware left join pptr_business business on pptr_hardware.bid=business.id
        left join pptr_subnet subnet on pptr_hardware.subnet_id=subnet.id
        <where>
            <include refid="BasicMapper.buildWhere"></include>
        </where>
        <include refid="BasicMapper.buildSortField"></include>
    </select>`

**Comment by hl0071** [comment]
`<select id="queryUnion" parameterType="org.hswebframework.web.commons.entity.Entity"
            resultMap="HardwareAssetResultMap">`
       ` <include refid="unionConfig"></include>`
        `${@cotron.admin.web.mybatis.builder.CustomSqlBuilder@current().SetPageInfo(#this['_parameter'])}`
        `select`
       ` <include refid="BasicMapper.buildSelectField"></include>`
        `from pptr_hardware left join pptr_business business on pptr_hardware.bid=business.id`
      `  left join pptr_subnet subnet on pptr_hardware.subnet_id=subnet.id`
       ` <where>`
           ` <include refid="BasicMapper.buildWhere"></include>`
        `</where>`
       ` <include refid="BasicMapper.buildSortField"></include>`
    `</select>`

**Comment by hl0071** [comment]
> 
> 
> 三个以上表级联，就乱报错。。。

不好意思，是我太粗心了，是因为我定义了两个ID一样的mapper...,多级查询没问题
