### ISSUE TITLE
[需求] spring-boot 2支持

### ISSUE THREAD

**Issue by zhou-hao** [hs-web/hsweb-framework#137]
# 场景
4.0.x 开始支持 spring-boot2。

**Comment by tianyaxiangdong** [comment]
对于缓存这一块儿在springboot2上的问题比较多

**Comment by JiaRG** [comment]
【建议】
1. 升级maven的版本到`3.5.0`以上，使用`${revision}`版本占位符。
2. 参考[spring-boot-project](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml)管理子模块的版本及依赖。

**Comment by zhou-hao** [comment]
@tianyaxiangdong  reactor有啥缓存方案没。目前用的编程式缓存...
