### ISSUE TITLE
像这种的查询怎么写MAPPER比较好[需求]

### ISSUE THREAD

**Issue by hl0071** [hs-web/hsweb-framework#138]
# 需求 说明
比如文章中的按字段值查不同表
[https://www.cnblogs.com/magic101/p/9687396.html](url)

# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.8

**Comment by zhou-hao** [comment]
如果对查询条件没有需求，建议类似比较复杂对逻辑都由程序逻辑处理

**Comment by hl0071** [comment]
selectfield 直接手写吗，GOD，100多个字段。。分页怎么弄？

**Comment by zhou-hao** [comment]
在sql里其实没啥好办法， 感觉在业务里设计一下应该更好， 比如先查询出主表数据，再使用策略模式，根据主表去查询关联数据。

**Comment by hl0071** [comment]
> 
> 
是挺好的，但是根据从表数据查主表信息，还要拦截参数，好像不用SQL有点麻烦

**Comment by zhou-hao** [comment]
在service里业务里做呗

**Comment by hl0071** [comment]
业务里面没有从表信息，每个栏目，都要硬写里面，有点繁琐。。

**Comment by zhou-hao** [comment]
目前确实没啥好办法，后续的版本可以考虑增加类似的需求的拓展性。

**Comment by hl0071** [comment]
谢谢
