### ISSUE TITLE
服务端数据验证支持JPA注解吗[疑问]

### ISSUE THREAD

**Issue by hl0071** [hs-web/hsweb-framework#139]
# 环境
java: 1.8.0_131
hsweb: 3.0.5
我看，Insert和update里面有相应的通用验证，不知道怎么才能生效，是需要设计TABLE时设置好字段的验证规则吗，还是需要自己扩展注解？
# 问题说明

**Comment by zhou-hao** [comment]
可以使用jsr303

**Comment by hl0071** [comment]
自动的还是需要改controle用BindingResult

**Comment by zhou-hao** [comment]
应该可以直接用。有两个group。CreateGroup和UpdateGroup。在Controller上用的话。可以不用BindingResult。框架统一处理了验证器异常。你可以试试
