### ISSUE TITLE
@Excel注解[疑问]

### ISSUE THREAD

**Issue by hl0071** [hs-web/hsweb-framework#142]
# 环境
java: 1.8.0_131
hsweb: 3.0.8
原来的转换器：
` Class<ExcelCellConverter> converter() default ExcelCellConverter.class;`

我想应该是这样的吧？？
` Class<? extends ExcelCellConverter> converter() default ExcelCellConverter.class;`
# 问题说明

**Comment by hl0071** [comment]
我在@excel注解里面配置convetor，自己写的转换器继承ExcelCellConverter,但是报类型错误，incomplete type,这里应该是限定ExcelCellConverter的子类吧？？？请赐教

**Comment by zhou-hao** [comment]
是的
