### ISSUE TITLE
级联查询分页报错[BUG]

### ISSUE THREAD

**Issue by hl0071** [hs-web/hsweb-framework#147]
# BUG 说明
` <select id="countNest" parameterType="org.hswebframework.web.commons.entity.Entity" resultType="int">
        <include refid="config"/>
        select
        count(1)
        from h_test
        left join h_nest_table nest_table on nest_table.id=h_test.id
        <where>
            <include refid="BasicMapper.buildWhere"/>
        </where>
    </select>`
这个查询count 为空
org.apache.ibatis.binding.BindingException: Mapper method 'cotron.admin.web.asset.manage.dao.UploadFileInfoMapper.countUnion attempted to return null from a method with a primitive return type (int).
# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.8

**Comment by zhou-hao** [comment]
升级到3.0.9试试

**Comment by hl0071** [comment]
已经根深地固的使用了3.0.8了啊

**Comment by hl0071** [comment]
用了3.0.9还是这错误，我在WINDOWS上没事，部署到linux就不行了。。。。，不知道咋回事，两个平台Lib和xml文件也对比了，分页只要自己调用count就报错。。。

**Comment by hl0071** [comment]
attempted to return null from a method with a primitive return type (int).

**Comment by zhou-hao** [comment]
用的啥数据库 看看执行的sql是不是有错

**Comment by hl0071** [comment]
没有的
`  <select id="count" parameterType="org.hswebframework.web.commons.entity.Entity" resultType="int">
    <include refid="config"/>
    <include refid="BasicMapper.buildTotalSql"/>
  </select>`

**Comment by hl0071** [comment]
只要这样调用就出错getDao().count(param);WINDOW上没有问题。。。就LINUX不行

**Comment by zhou-hao** [comment]
看看日志打印的sql 是啥

**Comment by hl0071** [comment]
。。。本地没问题，服务器输出里面没有SQL，好吧，只能在PagerInterceptor里面加log了。。。

**Comment by zhou-hao** [comment]
把mybatis的日志开启就可以看啊。你是自己打包的hsweb framework 还是引入的依赖

**Comment by hl0071** [comment]
引入的依赖

**Comment by hl0071** [comment]
好的

**Comment by hl0071** [comment]
一部分依赖一部分自己打的包

**Comment by zhou-hao** [comment]
https://github.com/hs-web/hsweb-framework/commit/0cf4be6fe3a327de4c8bca354a99443c310e6362 看这个commit

**Comment by hl0071** [comment]
额找到原因了。。。 select count(0) as total from pptr_attackhost limit 10,10；不知道为什么手动调用count后面会加上分页限制。。。，这个语句在WINDOWS和linux执行结果不一样，有区别，WINDOWS回忽略分页，linux翻到第二页就返回empty...........

**Comment by hl0071** [comment]
额

**Comment by hl0071** [comment]
为什么直接继承不会自动加这个limite..

**Comment by hl0071** [comment]
是不是我全局Pager设置的时机不对。。。。count时pager.get不应该有值

**Comment by zhou-hao** [comment]
嗯。分页拦截器确实做得比较low。 有好的方式可以pr一下。  新版本开始去除mybaits了。

**Comment by hl0071** [comment]
> 
> 
> 嗯。分页拦截器确实做得比较low。 有好的方式可以pr一下。 新版本开始去除mybaits了。

不是吧，有比mybaits更好的框架？

**Comment by zhou-hao** [comment]
看场景吧。下一步准备往响应式走，jdbc不太适合，而且我不喜欢复杂sql，mybatis就显得有点鸡肋了。然后我把easyorm升级了，https://github.com/hs-web/hsweb-framework/tree/3.1.x  https://github.com/hs-web/hsweb3-demo/tree/3.1.x  是完全基于新版easyorm实现的。

**Comment by hl0071** [comment]
666，大神
