### ISSUE TITLE
你好！3.0有没有什么规划？我感觉这个项目挺不错的，希望能为这个项目做一些贡献

### ISSUE THREAD

**Issue by liuyatao** [hs-web/hsweb-framework#15]

**Comment by zhou-hao** [comment]
@liuyatao 3.0目前在开发初期，大部分模块还没完成。文档还不是很全。你可以先clone下来看一下已完成的模块。 计划每个模块都会加入README.md 进行说明。

**Comment by sxyseo** [comment]
目前正在熟悉代码，希望后续也能有所贡献。

**Comment by bdbjxsr** [comment]
本来想自己搞一个的，偶然间发现你这个项目，希望能做一点贡献，关注中

**Comment by Succcc** [comment]
php的web后端，最近正在做类似的后台，正好学习
