### ISSUE TITLE
[BUG]当jdbcType为Number类型，类中字段为Enum类型时，执行insert操作会报错

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#150]
### 运行环境

`hsweb version`:  **3.0.11-SNAPSHOT**
`mybatis`:  **3.5.3**
```yaml
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-handlers-package: com.xxx.entity.enums
```

### 复现步骤

```java
/**
 * 实体类
 */
public class Student {

    private StatusEnum status
    
    // ignore getter/setter
}
/**
 * 状态枚举
 */
public enum StatusEnum implements EnumDict<Integer> {
    Created(0, "created"),

    Deleted(1, "deleted") 

    private final Integer value;
    private final String key;

     // ignore constructor/getter
}
```

```xml
<!-- Mybatis xml resultMap -->
<result property="status" column="status" jdbcType="TINYINT"/>
```
执行`insert`时报错：`Caused by: java.lang.UnsupportedOperationException: 值Created无法转换为数字`

### 原因分析
https://github.com/hs-web/hsweb-framework/blob/9eb96c4c7e6912253de3783673a922c216b5eec7/hsweb-commons/hsweb-commons-dao/hsweb-commons-dao-mybatis/src/main/java/org/hswebframework/web/dao/mybatis/builder/EasyOrmSqlBuilder.java#L253-L256
https://github.com/hs-web/hsweb-framework/blob/9eb96c4c7e6912253de3783673a922c216b5eec7/hsweb-commons/hsweb-commons-dao/hsweb-commons-dao-mybatis/src/main/java/org/hswebframework/web/dao/mybatis/builder/TypeUtils.java#L32-L36

在此场景下，`status`字段构造的`column`对象满足`TypeUtils.isNumberType(column)`该条件，因此会给该column设置`NumberValueConverter`, 但是此时`column.getJavaType()`的值为`Enum`类型

**Comment by JiaRG** [comment]
是否去掉`TypeUtils.isNumberType#numberJdbcType.contains(columnMetaData.getJdbcType()`这行判断比较好？

**Comment by JiaRG** [comment]
另外好像还发现个mybatis的问题，通过`EnumDictHandlerRegister.register("org.hswebframework.web;" + mybatisProperties.getTypeHandlersPackage());`注册的enum最后都没使用到，使用到的是mybatis自己的`EnumTypeHandler`(取的是Enum name)

`DefaultParameterHandler`
![image](https://user-images.githubusercontent.com/31472350/71566264-31403d80-2af1-11ea-8c48-b6e121006825.png)
![image](https://user-images.githubusercontent.com/31472350/71566327-ad3a8580-2af1-11ea-9a2f-e39256434f52.png)

**Comment by zhou-hao** [comment]
请使用JPA注解方式，不在mybatis中定义result试试

**Comment by JiaRG** [comment]
@zhou-hao 这个问题还是存在的，前提是混合使用`JPA`注解和`mybatis`的`resultMap`，`TestCrud`这个单测就能复现

**Comment by zhou-hao** [comment]
有具体的复现步骤么。我跑`TestCrud`未能复现

**Comment by JiaRG** [comment]
当一个字段是枚举数组类型的时候，`JpaAnnotationParser`返回的`JDBCType`是`BIGINT`, 这样就会符合`TypeUtils.isNumberType(column)`这个条件，并且`JpaAnnotationParser`解析`JDBCType`那好像也有问题了https://github.com/hs-web/hsweb-framework/blob/9eb96c4c7e6912253de3783673a922c216b5eec7/hsweb-commons/hsweb-commons-dao/hsweb-commons-dao-mybatis/src/main/java/org/hswebframework/web/dao/mybatis/builder/jpa/JpaAnnotationParser.java#L91-L105
这里的`type`其实是`entityClass`, 逻辑因该是取`property`的class吧

**Comment by JiaRG** [comment]
![image](https://user-images.githubusercontent.com/31472350/71716627-5a91fe00-2e50-11ea-9d49-39cbfa4da135.png)

**Comment by zhou-hao** [comment]
BIGINT 的场景是。如果是枚举数组的话，会用位运算的方式来处理多选。

**Comment by JiaRG** [comment]
我本地跑这个单测没通过。。。。
![image](https://user-images.githubusercontent.com/31472350/71717473-32f06500-2e53-11ea-8d0b-f5aa403ec918.png)

**Comment by zhou-hao** [comment]
是现在最新的3.0.x分支么？

**Comment by JiaRG** [comment]
嗯，升级过Spring Boot和mybatis的版本，具体见PR

**Comment by zhou-hao** [comment]
能用当前的3.0.x分支复现么

**Comment by JiaRG** [comment]
嗯，等会回去试试

**Comment by JiaRG** [comment]
@zhou-hao 当前的3.0.x分支能pass 。。。

**Comment by JiaRG** [comment]
@zhou-hao `JpaAnnotationParser`那里我的理解是否有问题？

**Comment by zhou-hao** [comment]
@JiaRG  hsweb 对枚举数组对处理 默认就是使用 bitint来存储 多个枚举数组对位掩码，通过位运算来实现多选，这样数据库里存储对就是一个数字。

**Comment by JiaRG** [comment]
嗯嗯，我的意思是那块的逻辑应该是取property的class吧，type其实是entityClass

**Comment by zhou-hao** [comment]
好像是哈!!!

**Comment by JiaRG** [comment]
@zhou-hao 高版本单测报错的问题是由于建表时`data_type`列的JdbcType为`SMALLINT`，但是注册的`EnumDictHandler`没包含此类型
https://github.com/hs-web/hsweb-framework/blob/9eb96c4c7e6912253de3783673a922c216b5eec7/hsweb-commons/hsweb-commons-dao/hsweb-commons-dao-mybatis/src/main/java/org/hswebframework/web/dao/mybatis/EnumDictHandlerRegister.java#L122-L127
所以按照mybatis`TypeHandlerRegistry#getTypeHandler(Type type, JdbcType jdbcType)`的逻辑就取到默认的`EnumTypeHandler`

**Comment by JiaRG** [comment]
@zhou-hao mybatis `SqlSessionFactoryBean#afterPropertiesSet()#buildSqlSessionFactory()`会解析`mapperLocations`，然后通过`MapperBuilderAssistant#buildResultMapping()`构造`ResultMapping`对象，构造对象期间会去`TypeHandlerRegistry`获取对应的typeHandler，而这时`EnumDictHandlerRegister.register`的方法还没调用，所以如果是枚举类型的typeHandler就会获取到默认的

**Comment by JiaRG** [comment]
考虑自定义个`SqlSessionFactoryBean`把注册的逻辑插入进去
![image](https://user-images.githubusercontent.com/31472350/72136300-769f1d80-33c3-11ea-91e2-98d3119617a8.png)

**Comment by JiaRG** [comment]
目前单测`testDao.queryNest(query)`能跑成功是由于mapper中没定义`<result property="dataType" column="data_type" javaType="org.hswebframework.web.dao.crud.DataType" jdbcType="BIGINT"/>`,
依托于JPA注解和mybatis的`DefaultResultSetHandler#createAutomaticMappings()`处理的
![image](https://user-images.githubusercontent.com/31472350/72137024-0beee180-33c5-11ea-88e1-acd2437754f5.png)

**Comment by zhou-hao** [comment]
是一种解决办法。目前还是在构造sql的时候去指定typeHandler的。可以提提pr。
