### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HaijieChen** [hs-web/hsweb-framework#151]
# BUG 说明
接口自动注入Authorization 获取到的用户为空，
通过Authorization.current().get().getUser()获取当前登录用户有时正确有时不正确，可能获取到的是其他用户
# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.9
 
# 复现步骤
登录时传入的token_type:token
# 期望结果
登录获取用户信息一致

# 截图说明

**Comment by zhou-hao** [comment]
在哪获取的？

**Comment by HaijieChen** [comment]
> 在哪获取的？

/**
     * 获取登录的用户信息
     * @return
     */
    @Authorize(action = "query")
    @GetMapping("/loginuser")
    @ResponseBody
    public ResponseMessage loginUser(){
        UserEntity userEntity = (UserEntity) Authentication.current().get().getUser();
     return ResponseMessage.ok(userEntity);
    }


这样获取 ，在controller

**Comment by HaijieChen** [comment]
> 在哪获取的？

 /**
     * 获取登录的用户信息
     * @return
     */
    @Authorize(action = "query")
    @GetMapping("/loginuser")
    @ResponseBody
    public ResponseMessage loginUser(Authentication authentication){
        UserEntity userEntity = (UserEntity) authentication.getUser();
     return ResponseMessage.ok(userEntity);
    }

如果用这种方式注入 ，authentication.getUser()是null

**Comment by zhou-hao** [comment]
使用 https://github.com/hs-web/hsweb3-demo 能复现吗？

**Comment by HaijieChen** [comment]
这个我得去看看  我引入包开发遇见的
