### ISSUE TITLE
[BUG]BeanPostProcessor#postProcessAfterInitialization未执行

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#152]
### BUG 说明
`hsweb-datasource-api`模块中`InSpringDynamicDataSourceConfigRepository`实现了`BeanPostProcessor#postProcessAfterInitialization`但是实际断点调试过程中却发现方法未被Spring调用，导致注入到Spring的多个DataSource未能被解析到`InSpringDynamicDataSourceConfigRepository#configMap`中，从而造成多数据源失败

### 运行环境
java: 1.8.0_131
maven: 3.3.9
**hsweb: 3.0.10**
**spring boot：1.5.19.RELEASE**
 
### 复现步骤
```xml
        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-datasource-api</artifactId>
            <version>${hsweb.framework.version}</version>
        </dependency>
```
定义多个DataSource
`InSpringDynamicDataSourceConfigRepository`类中`postProcessBeforeInitialization` `postProcessAfterInitialization`打断点

### 截图说明
![image](https://user-images.githubusercontent.com/31472350/71884486-6ee93a00-3173-11ea-8fc2-cc49b10169a7.png)

**Comment by zhou-hao** [comment]
是否还引入里其他数据源管理实现。比如 hsweb-system-datasource

**Comment by JiaRG** [comment]
没有

**Comment by zhou-hao** [comment]
InSpringContextDynamicDataSourceService 的是在 `InSpringDynamicDataSourceConfigRepository.postProcessAfterInitialization` 之前执行的。
 
在`InSpringDynamicDataSourceConfigRepository.postProcessAfterInitialization` 里debug 直到系统启动完成都没执行？

**Comment by JiaRG** [comment]
是的，我用demo调试过，不行。
单独实现BeanPostProcessor然后配置Bean到`DynamicDataSourceAutoConfiguration`也好像不行。
最后通过`@Import(InSpringDynamicDataSourceBeanPostProcessor.class)`这种方式好使了

**Comment by zhou-hao** [comment]
升级了spring-boot版本吗？

**Comment by JiaRG** [comment]
![image](https://user-images.githubusercontent.com/31472350/71889806-e8862580-317d-11ea-9338-a0ca9d79ae4f.png)

**Comment by zhou-hao** [comment]
再试试呢

**Comment by JiaRG** [comment]
可以了
