### ISSUE TITLE
[疑问]GenericEntityService物理删除为什么不使用DSL的方式？

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#154]
# 环境
java: 1.8.0_131
hsweb: 3.0.11.SNAPSHOT

# 问题说明
https://github.com/hs-web/hsweb-framework/blob/9eb96c4c7e6912253de3783673a922c216b5eec7/hsweb-commons/hsweb-commons-service/hsweb-commons-service-simple/src/main/java/org/hswebframework/web/service/GenericEntityService.java#L101-L105

**Comment by zhou-hao** [comment]
说实话，忘了。。。 可能是历史遗留问题。
