### ISSUE TITLE
源码编译有问题[BUG]

### ISSUE THREAD

**Issue by damonflycloud** [hs-web/hsweb-framework#159]
# BUG 说明
简要说明bug情况

# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.9
 
# 复现步骤
SimpleFileInfoEntity编译出错,由于createTime 在RecordCreationEntity接口是date类型,在SimpleFileInfoEntity类是long时 编译时识别需要实现getCreateTime方法,这应该怎么解决?
# 期望结果
此功能期望的执行结果

# 截图说明
![image](https://user-images.githubusercontent.com/2579254/82035852-b1e38d00-96d2-11ea-9d1a-d6bef47faace.png)

**Comment by zhou-hao** [comment]
RecordCreationEntity 应该一直就是long类型吧: 

![image](https://user-images.githubusercontent.com/7791838/82036336-5e257380-96d3-11ea-8ce4-9316396c61dc.png)

**Comment by damonflycloud** [comment]
![image](https://user-images.githubusercontent.com/2579254/82036628-b3fa1b80-96d3-11ea-8763-a46553554abc.png)
看你现在github上面的源代码还是long的

**Comment by zhou-hao** [comment]
这个没问题吧。你那不是提示 类型为Date么

**Comment by damonflycloud** [comment]
忽略... 别人给的源码有问题....
