### ISSUE TITLE
maven 循环依赖

### ISSUE THREAD

**Issue by zhangcola** [hs-web/hsweb-framework#16]
![image](https://cloud.githubusercontent.com/assets/15936604/23111044/ee8145d2-f760-11e6-9c9a-ff103795a420.png)

你好，clone下来的代码，idea提示maven循环依赖了
Project hsweb-framework: there is circular dependency between 'hsweb-commons-controller' module, 'hsweb-authorization-shiro' module

**Comment by zhou-hao** [comment]
已解决
