### ISSUE TITLE
[疑问] 当鉴权时，如果用户有某个权限，则会进行匹配，如果用户没有一个权限，则会匹配成功？

### ISSUE THREAD

**Issue by AnLakeside** [hs-web/hsweb-framework#161]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
DefaultAuthorizingHandler.handleDataAccess
    allMatch(act -> permission.getDataAccesses(act.getId())
如果用户没有DataAccesses权限（s_autz_setting_info.data_accesses 为空）， 则会直接返回true;原因是如果permission.getDataAccesses(act.getId())为空，那么allMatch 会直接返回true.也就是说用户只有设置了DataAccesses才去校验Data权限，如果没设置或者没有该权限，那么会直接返回true，可以请求成功。  是问题吗？

**Comment by zhou-hao** [comment]
数据权限和RBAC权限是独立验证的。
