### ISSUE TITLE
代码风格，比如 if {}

### ISSUE THREAD

**Issue by CharkeyQK** [hs-web/hsweb-framework#17]
看了些代码，有些单行 if 没 {} 倒是显得方法体简介。不过大块代码的 if 没有 {} 括起来还有点不习惯。

后续我希望能贡献贡献代码。

**Comment by zhou-hao** [comment]
恩,现在主要在搞 新版本[3.0](https://github.com/hs-web/hsweb-framework/tree/3.0), 还在完善结构。有兴趣也可以看看。

**Comment by CharkeyQK** [comment]
嗯，学习学习。
