### ISSUE TITLE
4.x有计划包含3.x的所有功能吗？

### ISSUE THREAD

**Issue by liweitao92** [hs-web/hsweb-framework#172]
4.x有计划包含3.x的所有功能吗？

**Comment by zhou-hao** [comment]
目前还没有的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liweitao92 <notifications@github.com&gt;
发送时间: 2020年9月10日 08:29
收件人: hs-web/hsweb-framework <hsweb-framework@noreply.github.com&gt;
抄送: 老周 <zh.sqy@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[hs-web/hsweb-framework] 4.x有计划包含3.x的所有功能吗？ (#172)





 
4.x有计划包含3.x的所有功能吗？
