### ISSUE TITLE
[疑问]hsweb-authorization-basic 和 springfox-swagger 一起集成 报错

### ISSUE THREAD

**Issue by liao-l-x** [hs-web/hsweb-framework#173]
# 环境
java: 1.8
hsweb:  4.0.6
swagger2  2.9.2

# 问题说明
springboot 2.3.4.RELEASE的项目就 hsweb-authorization-basic  4.0.6 和 r2dbc mysql相关的jar包、springfox-swagger2 2.9.2相关的jar

一直报错： Consider defining a bean of type 'springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper' in your configuration.

在去除 hsweb-authorization-basic  4.0.6 后运行正常 

hsweb-authorization-basic  4.0.6 和 swagger2一起集成需要额外的配置吗

**Comment by leonlee723** [comment]
https://medium.com/@karanbir.tech/spring-webflux-swagger-ui-and-open-api-3-api-specifications-fdbccd584c94 可以参考这个试试

**Comment by zhou-hao** [comment]
推荐使用
```xml
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
            <version>1.4.5</version>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-springdoc-ui</artifactId>
            <version>2.0.5</version>
        </dependency>
```
