### ISSUE TITLE
树状表的查询速度

### ISSUE THREAD

**Issue by wangleigithub** [hs-web/hsweb-framework#176]
1. 问题描述:
在数据量较大（>100万条，深度6）的表中，查询某个节点的所有上级节点，查询速度较慢（>1s）
2. 复现步骤:
任意个节点的所有上级
3. 日志内容:
查看源码应该是((Query)((Query)this.createQuery().where()).and("path$like$reverse$startWith", old.getPath())).listNoPaging()出来的语句

**Comment by zhou-hao** [comment]
path 添加索引没

**Comment by wangleigithub** [comment]
加了，我知道其实只要查path就够了，

**Comment by zhou-hao** [comment]
这个应该是数据库的瓶颈里。使用反向path查询应该无法使用索引。你看看执行计划。

**Comment by wangleigithub** [comment]
> 这个应该是数据库的瓶颈里。使用反向path查询应该无法使用索引。你看看执行计划。

没走，是ALL

**Comment by zhou-hao** [comment]
搜搜看能通过函数索引之类的手段让这种方式能使用索引不。

**Comment by wangleigithub** [comment]
> 搜搜看能通过函数索引之类的手段让这种方式能使用索引不。

我目前的做法是改path值，不是随机4位数，直接用主键，然后写个函数查
