### ISSUE TITLE
无法编译最新版本

### ISSUE THREAD

**Issue by linuxtmty** [hs-web/hsweb-framework#178]
1. 问题描述:
JDK1.8
无法将枚举 org.hswebframework.web.enums.TrueOrFalse中的构造器
hsweb-core/src/main/java/org/hswebframework/web/dict/defaults/DefaultDictDefineRepository.java:[71,9] 找不到符号
2. 复现步骤:
mvn compile
3. 日志内容:

**Comment by zhou-hao** [comment]
提供一下完整日志

**Comment by jianminbai** [comment]
unsubscri
