### ISSUE TITLE
关于多数据源示例

### ISSUE THREAD

**Issue by zzvv** [hs-web/hsweb-framework#18]
Hi！
我clone 了工程后，看到有个子模块做多数据源，但没搜索到具体使用的地方示例。

**Comment by zhou-hao** [comment]
你可以运行 [hsweb-demo](https://github.com/hs-web/hsweb-demo) 参照操作
1. 登录系统，进入数据源管理
2. 添加数据源,注意ID为切换的标识。
3. 声明式切换: `DynamicDataSource.use("数据源ID")`,是用完记得DynamicDataSource.useDefault();
4.注解式切换: 在要切换的方法上注解 `@UseDataSource("数据源ID")`,目前仅仅支持方法上注解.后面会优化。
