### ISSUE TITLE
集成Redisson时Spring Cache的ValueWrapper被包装为NullValue导致认证失败

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#182]
https://github.com/hs-web/hsweb-framework/blob/6f8b0b703baadccd72f928557d93d5413be27b56/hsweb-system/hsweb-system-authorization/hsweb-system-authorization-local/src/main/java/org/hswebframework/web/service/authorization/simple/SimpleAuthenticationManager.java#L99-L107

**Comment by zhou-hao** [comment]
嗯。可以PR一下。到3.0.x分支

**Comment by zhou-hao** [comment]
已发布`3.0.12-SNAPSHOT`
