### ISSUE TITLE
关于多表联查

### ISSUE THREAD

**Issue by wsmGo** [hs-web/hsweb-framework#190]
多表联查得还是得自己写sql吗 以什么方式注入呢

**Comment by zhou-hao** [comment]
注入ReactiveSqlExecutor



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wsmGo ***@***.***&gt;
发送时间: 2022年1月24日 13:40
收件人: hs-web/hsweb-framework ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Assign ***@***.***&gt;
主题: Re: [hs-web/hsweb-framework] 关于多表联查 (Issue #190)





 
多表联查得还是得自己写sql吗 以什么方式注入呢

**Comment by wsmGo** [comment]
> ReactiveSqlExecutor

谢谢 再请问下 非响应式的如何注入bean继承Repository 找不到bean

**Comment by wsmGo** [comment]
谢谢老周

**Comment by zhou-hao** [comment]
可以看一下。https://github.com/zhou-hao/hsweb4-examples



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月24日(星期一) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hs-web/hsweb-framework] 关于多表联查 (Issue #190)





  
ReactiveSqlExecutor
  
谢谢 再请问下 非响应式的如何注入bean继承Repository 找不到bean

**Comment by wsmGo** [comment]
再请教一下 非响应式和响应式 是不能同时使用吗

**Comment by wsmGo** [comment]
再请教一下 非响应式和响应式 是不能同时使用吗
