### ISSUE TITLE
[疑问] 非响应式和响应式是否能同时使用？ 

### ISSUE THREAD

**Issue by wsmGo** [hs-web/hsweb-framework#191]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
非响应式和响应式是否能同时使用？
可以的话 如何同时使用？ @EnableEasyormRepository 注解？
还是实体类上使用注解 @Reactive 注解？
试过好像都无法使用。

**Comment by zhou-hao** [comment]
不建议同时使用。可以参考示例 https://github.com/zhou-hao/hsweb4-examples
