### ISSUE TITLE
现在有个项目中集成了hsweb-core依赖包，但是不想使用该包对于响应结果的封装效果，请问我该如何配置

### ISSUE THREAD

**Issue by helloworld-xy** [hs-web/hsweb-framework#193]
# 环境
java: 1.8.0_131
hsweb: 4.0.13

# 问题说明
某些接口不想用 ResponseMessage进行封装，或者说如何禁用ResponseMessageWrapperAdvice对响应式接口的封装？

**Comment by helloworld-xy** [comment]
我好像知道了，调用ResponseMessageWrapperAdvice的setExcludes方法。但是如果我想禁用ResponseMessageWrapperAdvice怎样实现呢

**Comment by zhou-hao** [comment]
也有一个配置。你看一下创建这个类的地方



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 半生少年 ***@***.***&gt;
发送时间: 2022年2月16日 11:04
收件人: hs-web/hsweb-framework ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Assign ***@***.***&gt;
主题: Re: [hs-web/hsweb-framework] 现在有个项目中集成了hsweb-core依赖包，但是不想使用该包对于响应结果的封装效果，请问我该如何配置 (Issue #193)





 
我好像知道了，调用ResponseMessageWrapperAdvice的setExcludes方法。但是如果我想禁用ResponseMessageWrapperAdvice怎样实现呢

**Comment by helloworld-xy** [comment]
欧克，找到了，非常感谢。需要如下配置
```
#禁用hsweb对响应结果的封装
hsweb:
  webflux:
    response-wrapper:
      enabled: false
```
