### ISSUE TITLE
[疑问]自己编写的组件为何注入后 为什么在这个框架中扫不到

### ISSUE THREAD

**Issue by wsmGo** [hs-web/hsweb-framework#195]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
请问在使用hsweb-example中，使用自己的组件，添加完依赖扫描不到@component等注入的类，是因为这个框架中做了什么限制吗？

**Comment by wsmGo** [comment]
添加了依赖，试过了不同路径和相同路径，都无法扫描到。

**Comment by zhou-hao** [comment]
如果要使用component scan，需要在你的模块引入spring- context-indexer。或者使用Configuration方式创建bean



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wsmGo ***@***.***&gt;
发送时间: 2022年2月19日 12:52
收件人: hs-web/hsweb-framework ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Assign ***@***.***&gt;
主题: Re: [hs-web/hsweb-framework] [疑问]自己编写的组件为何注入后 为什么在这个框架中扫不到 (Issue #195)





 
添加了依赖，试过了不同路径和相同路径，都无法扫描到。

**Comment by wsmGo** [comment]
> 

好的 知道了 谢谢老周~
