### ISSUE TITLE
[疑问]组件容器问题

### ISSUE THREAD

**Issue by wsmGo** [hs-web/hsweb-framework#196]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
请问我自己的组件里边有web容器 您的mvc-examples里边也有 您是如何保证组件能和您服务在一个容器里头的呢？

**Comment by zhou-hao** [comment]
不太明白你的意思?

**Comment by wsmGo** [comment]
有两个问题：
1.我自己编写组件里边的event时间  被依赖的服务收不到
2.组件里边有web接口，能调用到组件里边的web接口，但是调用不到被依赖的服务接口了(因为我看jetlinks里边是组件和被依赖的都可以调用的)

**Comment by zhou-hao** [comment]
你的依赖是否添加到启动模块。 还有spring bean是否扫描到。

**Comment by wsmGo** [comment]
都有的 扫描到了

**Comment by zhou-hao** [comment]
你的依赖 有没有引入`spring-context-indexer`

**Comment by wsmGo** [comment]
也引入了

**Comment by zhou-hao** [comment]
那应该不会吧。创建一个仓库，复现 看看

**Comment by wsmGo** [comment]
好的 稍等稍等~

**Comment by wsmGo** [comment]
不好意思 花了点时间
 这个是被依赖的项目 git@github.com:wsmGo/com.git
这个是依赖的组件  git@github.com:wsmGo/com2.git

**Comment by wsmGo** [comment]
现在是组件里边的接口能访问 但是事件不能被被依赖项目监听到  另外被依赖项目的接口不能访问

**Comment by wsmGo** [comment]
对不起！ 我找到问题了。。浪费您时间了
