### ISSUE TITLE
[疑问]支持JPA的这种关系查询嘛 @OneToMany

### ISSUE THREAD

**Issue by shaokai-hou** [hs-web/hsweb-framework#201]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明

**Comment by zhou-hao** [comment]
不支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shaokai-hou ***@***.***&gt;
发送时间: 2022年6月16日 15:41
收件人: hs-web/hsweb-framework ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Assign ***@***.***&gt;
主题: Re: [hs-web/hsweb-framework] [疑问]支持JPA的这种关系查询嘛 @OneToMany (Issue #201)





 
Assigned #201 to @zhou-hao.

**Comment by shaokai-hou** [comment]
🙏

**Comment by shaokai-hou** [comment]
.
