### ISSUE TITLE
问下 是否支持分布式事物呢

### ISSUE THREAD

**Issue by tom055** [hs-web/hsweb-framework#202]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
想在项目中使用这个框架，请问是否支持分布式事物？还是说需要自己手动回滚事物呢

**Comment by zhou-hao** [comment]
支持事务，不支持分布式事务，或者你看看你使用的分布式事务框架是否支持r2dbc



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tom055 ***@***.***&gt;
发送时间: 2022年7月25日 17:50
收件人: hs-web/hsweb-framework ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Assign ***@***.***&gt;
主题: Re: [hs-web/hsweb-framework] 问下 是否支持分布式事物呢 (Issue #202)





 
环境
 
java: 1.8.0_131
 hsweb: 3.0.5
 
问题说明
 
想在项目中使用这个框架，请问是否支持分布式事物？还是说需要自己手动回滚事物呢
