### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SinPingWu** [hs-web/hsweb-framework#207]
# BUG 说明
编译提示PermissionSynchronization.java:[108,31] 不兼容的类型: java.lang.Object无法转换为java.util.Set<java.lang.Object>

# 运行环境
java: 1.8.0_131
maven: 3.6.3
hsweb: 4.0.15-SNAPSHOT
 
# 复现步骤
mvn clean install -Dmaven.test.skip=true

# 期望结果
能够正常编译通过

# 截图说明
![image](https://user-images.githubusercontent.com/12540788/212228494-5d0ea5da-f8d3-49a7-9490-b77d8fa9205f.png)

**Comment by zhou-hao** [comment]
jdk版本 使用 1.8.0_3xx  小版本号大于200

**Comment by SinPingWu** [comment]
谢谢！ 是Java版本问题，已解决。
