### ISSUE TITLE
[疑问]统一响应包装当接口返回值为String类型时可能会造成未知问题

### ISSUE THREAD

**Issue by renjiancheng** [hs-web/hsweb-framework#208]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
  在hsweb-commons/hsweb-commons-crud/src/main/java/org/hswebframework/web/crud/web/ResponseMessageWrapperAdvice.java中，如果接口返回值为String类型，那么会调用如下代码将返回值包装到统一响应的data里再转换成Json字符串返回，但是这种方式会破坏统一响应的整体性，因为开启了统一响应那么意味着整个系统都将返回content-Type为application/json且body为约定格式的Json字符串，但是在此种情况下响应的content-Type将会是text/html。除开content-Type的不一致外，这种情况还可能造成接口使用方的报错，因为他们必须先将返回值从字符串转换成对象才能使用它。
  但是如果在此处返回非String类型，那么Spring会认为这个接口返回的类型不能转换成String而报错，是否可以通过在系统中添加ResponseMessage到String的转换器或者在此处直接抛出异常告诉使用者不能完成这种转换，将接口返回类型修改为`ResponseMessage<String>`从而消除这种报错。
```java
if (method != null && returnType.getMethod().getReturnType() == String.class) {
            return JSON.toJSONString(ResponseMessage.ok(body));
}
```

**Comment by zhou-hao** [comment]
你现在用的哪个版本? 可以试试返回`ResponseEntity<String>`？
