### ISSUE TITLE
[需求]是否能将authorization-api单独从commons-crud中抽离出来

### ISSUE THREAD

**Issue by chengzichen** [hs-web/hsweb-framework#209]
# 场景
可以选择精简和适合自己的依赖
# 需求说明
是否能将authorization-api单独从commons-crud中抽离出来

**Comment by zhou-hao** [comment]
直接引入api的依赖呗

**Comment by chengzichen** [comment]
我用了crud,但是目前没有使用到api,请问下api和crud是强关联依赖吗?

**Comment by zhou-hao** [comment]
不用应该也没啥影响的吧？
