### ISSUE TITLE
[疑问] 请问下如何实现 group by 查询

### ISSUE THREAD

**Issue by MoonBottle** [hs-web/hsweb-framework#213]
# 环境
java: 1.8.0_131
hsweb: 4.0.16-SNAPSHOT

# 问题说明
想要实现 group by 分组聚合查询，可以由前端控制么？

**Comment by MoonBottle** [comment]
可以用 QueryHelper 自定义 group by 来实现吗？

**Comment by zhou-hao** [comment]
sql中应该是可以写group by的

**Comment by MoonBottle** [comment]
我试试

**Comment by zhou-hao** [comment]
reimport一下maven，这个之前修复过。

**Comment by MoonBottle** [comment]
不报错了，不过字段没有映射到实体类里
```java
    private String minuteInterval;

    private BigDecimal sumWater;

    private BigDecimal sumFeed;
```

**Comment by MoonBottle** [comment]
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/934abae4-e196-463e-bb43-ec18f7dac008)
另一个问题是，order by 会跑到 group by 前面导致 sql 异常

**Comment by zhou-hao** [comment]
好的 我看看

**Comment by zhou-hao** [comment]
再reimport一下试试

**Comment by MoonBottle** [comment]
```java
return queryHelper.select(
                "SELECT to_char(m.minute_interval, 'YYYY-MM-DD HH24:MI:SS') AS minute_interval,\n" +
                "       COALESCE(SUM(f.measure), 0)                         AS sum_water,\n" +
                "       COALESCE(SUM(f.measure), 0)                         AS measure,\n" +
                "       COALESCE(SUM(f2.measure), 0)                        AS sum_feed\n" +
                "FROM minutes m\n" +
                "         LEFT JOIN feeder_manual_feed f ON to_timestamp(f.date / 1000) AT TIME ZONE 'Asia/Shanghai' >= m.minute_interval\n" +
                "    AND to_timestamp(f.date / 1000) AT TIME ZONE 'Asia/Shanghai' < m.minute_interval + '1 minute'::interval\n" +
                "    AND f.type = 'water'\n" +
                "         LEFT JOIN feeder_manual_feed f2\n" +
                "                   ON to_timestamp(f2.date / 1000) AT TIME ZONE 'Asia/Shanghai' >= m.minute_interval\n" +
                "                       AND to_timestamp(f2.date / 1000) AT TIME ZONE 'Asia/Shanghai' < m.minute_interval + '1 minute'::interval\n" +
                "                       AND f2.type = 'feed'\n" +
                "GROUP BY minute_interval",
                FeederManualFeedSumDTO::new)
            .where(query)
            .fetch()
            .doOnNext(el -> System.out.println(el));
```
```java
    private String minuteInterval;

    private BigDecimal measure;

    private BigDecimal sumWater;

    private BigDecimal sumFeed;
```

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/25437338-f27a-46a7-85c3-da56d3c1c0ba)


重新 import 了，试了下 order by 已经正常了，但字段还是没有正常映射

但是我加了个 measure 做测试，这个字段是表中存在的字段，可以映射

似乎自定义别名，不在表中的字段不行

**Comment by zhou-hao** [comment]
聚合函数目前无法识别出列，所以别名需要和属性名一致。 `sum(..)   \"minuteInterval\"` .这样试试

**Comment by MoonBottle** [comment]
不行，select 里的字段不在映射范围内
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/255a0b97-dc3d-4645-aed9-75ae1b35a04a)

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/c67882a5-2b06-4617-83aa-0ed4be22dfbc)

问题不大，目前无法识别的话我去用别的方法实现需求，多谢大佬支持

**Comment by zhou-hao** [comment]
我优化了一下。自动转成驼峰映射。

**Comment by zhou-hao** [comment]
> 不行，select 里的字段不在映射范围内 ![image](https://user-images.githubusercontent.com/12904505/244012706-255a0b97-dc3d-4645-aed9-75ae1b35a04a.png)
> 
> ![image](https://user-images.githubusercontent.com/12904505/244013334-c67882a5-2b06-4617-83aa-0ed4be22dfbc.png)
> 
> 问题不大，目前无法识别的话我去用别的方法实现需求，多谢大佬支持

这个应该是没有进行转义，要使用`\"column\"`,不过现在统一将下划线转换为了驼峰，你再reimport试试

**Comment by MoonBottle** [comment]
稍等，我试下

**Comment by MoonBottle** [comment]
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/0ec4aa3a-584c-424c-86a8-e2124a5a5754)

奇怪，下面俩字段能出来，但是 minute_interval 不行

**Comment by zhou-hao** [comment]
数据库直接执行结果 长啥样

**Comment by MoonBottle** [comment]
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/9af24d69-9173-4214-84ff-56c5518c09a2)

**Comment by MoonBottle** [comment]
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/ff20d1ad-befb-4918-810a-70c926f4ab36)
这是表结构

**Comment by zhou-hao** [comment]
没能复现出来，能基于 https://github.com/zhou-hao/hsweb4-examples/tree/main/hsweb4-webflux-example 写一个复现程序么

**Comment by MoonBottle** [comment]
好，我再研究研究

**Comment by MoonBottle** [comment]
> 没能复现出来，能基于 https://github.com/zhou-hao/hsweb4-examples/tree/main/hsweb4-webflux-example 写一个复现程序么

有点尴尬 - - example 里是 h2 数据库，我的自定义sql 是postgresql 才有的语法

**Comment by MoonBottle** [comment]
大佬要不你加下我v，指导我debug一下？ w450527516

**Comment by zhou-hao** [comment]
按理说和sql语法应该没有关系

**Comment by MoonBottle** [comment]
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/26685e73-f554-49aa-aa39-57f16845b221)

这里报错，我试试改下sql

> 按理说和sql语法应该没有关系

**Comment by MoonBottle** [comment]
尴尬了，换了个写法，也没复现

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/49305508-f242-4b6f-a711-b00000b0e65f)

**Comment by zhou-hao** [comment]
那你连pgsql呢

**Comment by MoonBottle** [comment]
可以复现，稍等我整理下代码
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/45212be8-2614-4ecc-b5b9-82487f1c15f6)

**Comment by MoonBottle** [comment]
https://github.com/MoonBottle/hsweb4-examples
代码提交了 org.hswebframework.example.crud.web.TestControllerTest#test2

**Comment by MoonBottle** [comment]
test3 有另一个问题，相同的查询，如果是实体中的字段，返回的是实体中的字段类型
```java
    @Column
    @Schema(description = "量")
    private BigDecimal measure;

    @Column
    @Schema(description = "类型")
    private String type;

    @Column(length = 64)
    @Schema(description = "时间")
    private Long date;  // 实体类中 date 定义为的 long 型
```

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/07d21501-63ce-4095-a2dd-a2071259539c)

**Comment by zhou-hao** [comment]
嗯，和之前是相同的原因。再reimport一下。

**Comment by zhou-hao** [comment]
我优化一下..

**Comment by zhou-hao** [comment]
再再再次 reimport一下试试

**Comment by MoonBottle** [comment]
很稳，正确拼上了，结果也正确
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/501b1fc9-6216-4a6d-ac69-a33a024aecc5)
