### ISSUE TITLE
[需求]希望maven的pom里，绑定的springboot 、vertx、netty、reactor依赖项变成optional的，便于集成

### ISSUE THREAD

**Issue by richwxd** [hs-web/hsweb-framework#215]
# 场景

# 需求说明
希望maven的pom里，绑定的springboot 、vertx、netty、reactor依赖项变成optional的，便于集成。
当前都是写死的

**Comment by zhou-hao** [comment]
optional是在功能可选时使用，明显类似模块不是可选的。
如果要特定的依赖版本，只需要在自己的pom中使用`dependencyManagement`统一管理版本即可。
