### ISSUE TITLE
[BUG] 使用 QueryHelper  进行分页查询，分页返回结果错误

### ISSUE THREAD

**Issue by MoonBottle** [hs-web/hsweb-framework#217]
# BUG 说明
使用 QueryHelper queryHelper; 进行分页查询
总数 15 条，分页错误
```json
{
    "firstPageIndex": 1,
    "pageSize": 10,
    "pageIndex": 1, // 这里不管传 1 还是 2 ，返回的数据都是第一页的数据
}
```
# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 4.0.16-SNAPSHOT
 
# 复现步骤

# 期望结果
此功能期望的执行结果

# 截图说明
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/4a7e5182-589e-4ae1-8c9d-15e6f52459ed)

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/be6b1047-609e-456e-84b7-e4c727f6a4bd)

sql 拼接的也一样
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/b704faf0-da37-4c5e-a404-5814f291cc38)

**Comment by zhou-hao** [comment]
是使用的native查询？ 看你的数据并没有2页那么多，平台默认会自动回到最后一页。

**Comment by MoonBottle** [comment]
不是 native， 是类的方式查询的

**Comment by zhou-hao** [comment]
> 看你的数据并没有2页那么多，平台默认会自动回到最后一页。

如楼上所说

**Comment by MoonBottle** [comment]
不好意思，我没描述清楚，我重新说一下问题

15 条数据，第 1 页显示 10 条，第 2 页应该显示 5 条
但是当 firstPageIndex 传 1的情况下，现在传第 1 页，第 2 页，返回的都是第 1 页的 10 条数据

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/019c46d9-42f2-40e2-b588-4361584df4c3)


当 firstPageIndex 传 0 进行分页的时候，结果是正确的
![image](https://github.com/hs-web/hsweb-framework/assets/12904505/8122a6a2-1854-4736-8f87-696d81389f63)

**Comment by zhou-hao** [comment]
pageIndex页码是从0开始，所以1其实已经是第二页了。

**Comment by MoonBottle** [comment]
queryHelper 查询指定 firstPageIndex 参数无效么

我看不使用 queryHelper 的情况下这个参数是有效的

**Comment by zhou-hao** [comment]
firstPageIndex 你传1试试

**Comment by MoonBottle** [comment]
> firstPageIndex 你传1试试

截图中是传了1的，但似乎没生效

**Comment by zhou-hao** [comment]
嗯 确实有问题，firstPageIndex没生效

**Comment by zhou-hao** [comment]
刷新一下maven再试试

**Comment by MoonBottle** [comment]
可以了，大佬牛啤

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/1398d37b-5226-409d-87b2-ae3208712e6e)

**Comment by MoonBottle** [comment]
但是和 "firstPageIndex": 0 的时候，对于超过的页码处理方式不一样

firstPageIndex 为 0 的时候，返回是最后一页的数据

firstPageIndex 为 1 的时候，返回是没有数据


![image](https://github.com/hs-web/hsweb-framework/assets/12904505/d3d11173-351d-4be2-8329-a78c005b2a2d)

**Comment by zhou-hao** [comment]
再刷新一下试试

**Comment by MoonBottle** [comment]
阔以了，谢谢大佬

![image](https://github.com/hs-web/hsweb-framework/assets/12904505/50edaaea-6689-47b8-9adb-4993ae6c407b)
