### ISSUE TITLE
ResponseMessage 里面的问题

### ISSUE THREAD

**Issue by kleen** [hs-web/hsweb-framework#22]
ResponseMessage 里面的 exclude include 的作用是什么， 测试感觉不起作用

**Comment by zhou-hao** [comment]
@kleen 你怎么使用的

**Comment by kleen** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
第一个是测试结果，第二个图片是测试代码。 按照我的理解， 是排除officeId

**Comment by kleen** [comment]
@RequestMapping("/")
    @ResponseBody
    public ResponseMessage index(){
        SysUser sysUser = new SysUser();
        sysUser.setId("1");
        sysUser.setPasswd("123456");
        sysUser.setUserName("kleen");
        sysUser.setOfficeId("1231");
        return ResponseMessage.ok(sysUser).exclude(SysUser.class,"officeId");
    }

结果
{"success":true,"data":{"id":"1","officeId":"1231","userName":"kleen"},"code":200,"excludes":{"com.runyuan.system.model.user.SysUser":["officeId"]},"onlyData":false}

**Comment by zhou-hao** [comment]
你自定义了 `HttpMessageConverter` ?

**Comment by kleen** [comment]
有自定义一个

**Comment by zhou-hao** [comment]
目前使用自带的 `HttpMessageConverter`才行。你取消自定义的试试。或者在自定义的converter里自己处理。或者参照 [FastJsonHttpMessageConverter](https://github.com/hs-web/hsweb-framework/blob/60311efb6d15328e1f5174646d85ea044ad4eac5/hsweb-web-core/src/main/java/org/hsweb/web/core/message/FastJsonHttpMessageConverter.java#L93-L93)

**Comment by kleen** [comment]
谢谢
