### ISSUE TITLE
[求助]jetlink里的告警规则，关掉再打开，无法收到mqtt消息。但是重启服务后是正常的

### ISSUE THREAD

**Issue by fx820** [hs-web/hsweb-framework#222]
# 环境
java: 1.8.0_131
hsweb: 4.0.16
jetlink：1.2.1
# 问题说明
hsweb和jetlink均已是最新版本。且开启规则的过程中本地debug未发现报错

**Comment by zhou-hao** [comment]
请提交更详细的信息到 https://github.com/jetlinks/jetlinks-community 。如： pom.xml中的版本号，本地最新的git commitid，复现步骤等。
