### ISSUE TITLE
[疑问] 执行CrudTests报错， Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass

### ISSUE THREAD

**Issue by Lsp1995** [hs-web/hsweb-framework#231]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
执行test的时候，在targetClass = (Class)ctClass.toClass(ClassUtils.getDefaultClassLoader(), null);这一步报错：
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @78e67e0a

**Comment by zhou-hao** [comment]
使用java8

**Comment by Lsp1995** [comment]
噢3q，编译setting中是java8，没有检查项目javasdk配置，可以了
