### ISSUE TITLE
[疑问] 请教下如何快捷的设置某些字段值更新为 null

### ISSUE THREAD

**Issue by MoonBottle** [hs-web/hsweb-framework#233]
# 环境
java: 1.8.0_131
hsweb: 4.0.16

# 问题说明
表里有 10 个字段，本次更新值有3个为非 null 值，其余7个字段要更新为 null值
现在我可以依次判断这7个字段的值是否为 null，然后使用  `org.hswebframework.ezorm.rdb.mapping.DSLUpdate#setNull(java.lang.String)` 方法来设置，想请教下有没有更快捷的方法能实现这个需求

**Comment by zhou-hao** [comment]
目前没有太好的办法。只能setNull。

**Comment by MoonBottle** [comment]
> 目前没有太好的办法。只能setNull。

了解了，多谢~
