### ISSUE TITLE
[疑问]实现了ReactiveServiceSaveController接口的controller如何进行参数校验

### ISSUE THREAD

**Issue by kakascx** [hs-web/hsweb-framework#246]
# 问题说明
controller通过实现ReactiveServiceSaveController中提供的save接口保存数据
有没有提供接口校验入参body

实体类NetworkConfigEntity片段
```
@Column
@Generated
@JsonCodec
@ColumnType(jdbcType = JDBCType.CLOB, javaType = String.class)
@Schema(description = "配置(根据类型不同而不同)")
private Map<String, Object> configuration;
```
configuration是一个map，用来保存配置，会保存是否开启TLS认证和证书id

我需要校验：
当isTLS为true的时候certId不能为空

**Comment by zhou-hao** [comment]
方式一。重写 tryValidate方法
方式二。监听crud事件进行判断

ps. 在jetlinks中，应该会自动进行校验。见`NetworkConfig`.

**Comment by kakascx** [comment]
> 方式一。重写 tryValidate方法 方式二。监听crud事件进行判断
> 
> ps. 在jetlinks中，应该会自动进行校验。见`NetworkConfig`.

jetlinks里没搜到NetworkConfig.java，如果指的是NetworkConfigEntity.java，那么貌似目前没有自动校验Map中的isTLS和证书的依赖关系，计划写一个自定义注解实现校验

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-components/network-component/network-core/src/main/java/org/jetlinks/community/network/NetworkConfig.java#L55

**Comment by kakascx** [comment]
> https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-components/network-component/network-core/src/main/java/org/jetlinks/community/network/NetworkConfig.java#L55

看到了，多谢，我的代码版本比较老
