### ISSUE TITLE
[疑问]Flux.interval定时任务不执行问题

### ISSUE THREAD

**Issue by kakascx** [hs-web/hsweb-framework#259]
# 问题说明
利用Flux.interval创建定时任务，检查设备的状态并入库，但是map()中的逻辑不会执行，如下图
![image](https://github.com/hs-web/hsweb-framework/assets/15819504/e33c7083-de6a-42b3-b822-a78514db4b8e)
入库的逻辑如下图
![image](https://github.com/hs-web/hsweb-framework/assets/15819504/70d6e96c-5149-42b1-aa37-4d9df1d83aca)

**Comment by zhou-hao** [comment]
用flatMap ，且要使用onErrorResume。
类似这样
<img width="366" alt="image" src="https://github.com/hs-web/hsweb-framework/assets/7791838/fde9a6f6-b8e2-407a-af21-93f538240c9b">

**Comment by kakascx** [comment]
> 用flatMap ，且要使用onErrorResume。 类似这样 <img alt="image" width="366" src="https://user-images.githubusercontent.com/7791838/281648369-fde9a6f6-b8e2-407a-af21-93f538240c9b.png">

解决了，后面入库也出了问题，替换成flatmap成功了，看来还是没真正理解map和flatmap的场景，多谢
