### ISSUE TITLE
[使用方法]在本地运行成功，希望对其他人有帮助~

### ISSUE THREAD

**Issue by wangtengmei** [hs-web/hsweb-framework#262]
# 环境
java: 1.8.0_131
hsweb: 3.0.5
希望对其他人有帮助~
1.后端配置：
项目使用了 H2 数据库。您需要在 application.yml 文件中配置数据库连接信息。
MySQL 配置：
数据库连接URL：r2dbc:h2:file:///./data/h2db/jetlinks
用户名：sa
密码：无
2.登录网站
服务器端口号：8080，启动成功后访问 http://localhost:8080，用户名和密码在数据库的用户信息表中。
3.后端框架：
后端框架是 Spring WebFlux 框架。
4.导入 SQL 文件：
项目的数据库文件是自行建立的，不需要导入文件。
5.启动项目：
项目的启动方式是直接运行 Application.java 文件。确保您的开发环境配置正确，项目的依赖项已经安装。

**Comment by zhou-hao** [comment]
也可以参考 https://github.com/zhou-hao/hsweb4-examples
