### ISSUE TITLE
[BUG] ReactiveServiceSaveController#add(@RequestBody Mono<E> payload)  新增单个数据,并返回新增后的数据 这个接口的新增不会触发EntitySavedEvent事件

### ISSUE THREAD

**Issue by tablesheep233** [hs-web/hsweb-framework#279]
# BUG 说明
    @PostMapping
    @SaveAction
    @Operation(summary = "新增单个数据,并返回新增后的数据.")
    default Mono<E> add(@RequestBody Mono<E> payload) {
        return Authentication
                .currentReactive()
                .flatMap(auth -> payload.map(entity -> applyAuthentication(entity, auth)))
                .switchIfEmpty(payload)
                .flatMap(entity -> getService().insert(Mono.just(entity)).thenReturn(entity));  //这里使用insert()不会触发 EntitySavedEvent 事件
    }

# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.5
 
# 复现步骤

# 期望结果
期望 ReactiveCrudService#insert 能跟 ReactiveCrudService#save 一样触发 EntitySavedEvent 事件

# 截图说明

**Comment by zhou-hao** [comment]
insert触发EntityCreatedEvent

**Comment by tablesheep233** [comment]
> insert触发EntityCreatedEvent

好的，感谢
