### ISSUE TITLE
[疑问]org.hswebframework.web.crud.query.QueryAnalyzerImpl#visit(net.sf.jsqlparser.statement.select.TableFunction)方法没有实现

### ISSUE THREAD

**Issue by AntsMa** [hs-web/hsweb-framework#291]
# 环境
java: 1.8.0_131
hsweb: 4.0.16

# 问题说明
**在pg数据库中，如下都是正常可以操作的**
表users 的字段user_data是json类型，通过json_each_text获取key、value
`SELECT   
    u.id,  
    e.key AS json_key,  
    e.value AS json_value  
`
`FROM   
    users u,  
    `
`json_each_text(u.user_data) e;`
查询结果如下图样例
![image](https://github.com/hs-web/hsweb-framework/assets/34825320/541b8fdf-721b-460d-a515-2edd8b72fcb4)

**代码中报错空指针**
![image](https://github.com/hs-web/hsweb-framework/assets/34825320/277ab449-1acd-4ce0-99a1-f0e46993a5d2)

错误分析：
在方法org.hswebframework.web.crud.query.QueryAnalyzerImpl#visit(net.sf.jsqlparser.statement.select.PlainSelect)中joinAn.select是Null导致的，原因是调用的org.hswebframework.web.crud.query.QueryAnalyzerImpl#visit(net.sf.jsqlparser.statement.select.TableFunction)方法没有实现
![image](https://github.com/hs-web/hsweb-framework/assets/34825320/ea838b00-4f17-4c4e-8a9e-b60e667f53d0)
![image](https://github.com/hs-web/hsweb-framework/assets/34825320/64d33e9f-7a33-4450-9d97-a074f825cf98)

把sql：`json_each_text(u.user_data) e;`
改为 `CROSS  join json_each_text ( u.user_data) e`或者 innner join  json_each_text ( u.user_data) e都是一样的空指针报错

**这个场景下改怎么处理这个问题呢**

**Comment by zhou-hao** [comment]
用 `ReactiveSqlExecutor`执行sql试试

**Comment by zhou-hao** [comment]
刷新最新依赖，或者更新最新代码 ，再试试？

**Comment by AntsMa** [comment]
> 刷新最新依赖，或者更新最新代码 ，再试试？


实际项目里使用了 ReactiveSqlExecutor执行sql，看到该内容更新到hsweb是4.0.17上了，用的hsweb:实际是4.0.16没有验证新增方法是否可行
