### ISSUE TITLE
[疑问]查询语句的select distinct 字段识别有误，意外去掉了空格，导致报错

### ISSUE THREAD

**Issue by fx820** [hs-web/hsweb-framework#293]
# 环境
java: 1.8.0_131
hsweb: 3.0.5

# 问题说明
sql中有空格，但是执行时被去掉了，导致报错
![image](https://github.com/user-attachments/assets/33cb4c66-c917-4010-832b-2664faec3d00)

**Comment by zhou-hao** [comment]
升级到最新版本试试

**Comment by fx820** [comment]
已经升级到4.0.17snapshot了

**Comment by zhou-hao** [comment]
fork 本仓库，在 `QueryAnalyzerImplTest` 写一个单元测试复现看看

**Comment by fx820** [comment]
晚点我再试试。现在先用group by绕过这个bug了

**Comment by zhou-hao** [comment]
我这用了类似的SQL，没有复现。
<img width="984" alt="image" src="https://github.com/user-attachments/assets/2cfc117a-8e32-4407-b146-620fa43670fe">

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/55f7aed0-ff61-4c03-a9dd-0cff07b265af">

**Comment by fx820** [comment]
与

**Comment by zhou-hao** [comment]
确定是最新的代码？

**Comment by fx820** [comment]
重新git pull一下，distinct和后面的字段不会粘连了。但是我看引入的4.0.17-snapshot也是7.2打包的，按理说不该会有问题？

**Comment by zhou-hao** [comment]
手动刷新一下？
