### ISSUE TITLE
[疑问]您好，启动报错Field repository in org.hswebframework.web.crud.service.GenericReactiveCrudService required a bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository' that could not be found.

### ISSUE THREAD

**Issue by GUjhreal** [hs-web/hsweb-framework#294]
# 环境
java: 1.8.0_131
hsweb: 4.0.16

# 问题说明
Field repository in org.hswebframework.web.crud.service.GenericReactiveCrudService required a bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:
Consider defining a bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository' in your configuration.

目前只用了crud，是需要进行什么配置吗

**Comment by zhou-hao** [comment]
没有扫描到 实体类吧

**Comment by GUjhreal** [comment]
大佬，针对多条件的联表查询除了手写SQL还有什么快捷实现的方法吗

**Comment by zhou-hao** [comment]
不是有动态条件参数？

**Comment by GUjhreal** [comment]
> 不是有动态条件参数？

谢谢不小心漏掉了
