### ISSUE TITLE
[疑问]

### ISSUE THREAD

**Issue by DBS208** [hs-web/hsweb-framework#295]
hsweb: 4.0.16

![image](https://github.com/user-attachments/assets/62520450-1213-41be-8825-3b0a02ffb496)
MySQL中delete是tinyint(1)，这里的where怎么会不起作用呢，不支持吗

**Comment by zhou-hao** [comment]
实体类中有定义这个字段吗？

**Comment by DBS208** [comment]
哦哦之前改代码的时候不小心把delete上面的Column删掉了，谢谢了
