### ISSUE TITLE
[疑问]SortOrder自定义排序部分失效

### ISSUE THREAD

**Issue by GUjhreal** [hs-web/hsweb-framework#299]
# 环境
java: 1.8.0_131
hsweb: 4.0.16

# 问题说明

这里有两个SortOrder，为何第一个.value(currentUser.getId()).function("CASE WHEN user_id = ? THEN 0 ELSE 1 END")是生效的，但是第二个case是不生效的，想问一下是因为第二个没加value吗？生成SQL部分如下：
` order by case when project_task.`user_id` = '1820644096132263936' then 1 else 10000 end , project_task.`status` asc limit 0,20`
![a59775fb658e88d009c4be43a44dec5](https://github.com/user-attachments/assets/b1a0863c-ba42-4909-b4ae-33b268964edd)
还有SortOrder支持Field函数吗，我自己测了一下好像不太行，或者是我哪里写的有问题吗

**Comment by zhou-hao** [comment]
不支持直接写sql。 可以试试这样 :  
```java
.orderBy(
SortOrder.asc("user_id").value(userId),
SortOrder.asc("status").value("进行中"),
SortOrder.asc("status").value("已过期")
)
```

**Comment by zhou-hao** [comment]
生效的原因是 value(..)  表示 按值排序。 无需定义function。如果需要走自定义function。需要实现 `FunctionFragmentBuilder` 并注入spring。

**Comment by GUjhreal** [comment]
感谢，找到源码了
