### ISSUE TITLE
请问项目maven导入依赖完成后，在哪里启动运行？

### ISSUE THREAD

**Issue by laureler** [hs-web/hsweb-framework#35]
spring boot了解不够深入，但是我并没找到sppring boot启动的入口main函数，希望可以给一点提示，我仔细看了readme,md 里面的很多使用方式都只是简介，所以希望能够明确的指示出来、

**Comment by zhou-hao** [comment]
你可以用[demo](https://github.com/hs-web/hsweb-demo)来启动. 可参照demo的配置。 如果是3.0 可以看看 [example](https://github.com/hs-web/hsweb-framework/tree/3.0/hsweb-examples)
