### ISSUE TITLE
吓死人了这包分的也太多了

### ISSUE THREAD

**Issue by duxinshi** [hs-web/hsweb-framework#49]
![hsweb](https://user-images.githubusercontent.com/3894605/29493178-24ec5bba-85c4-11e7-8361-87ec03247c60.png)

**Comment by duxinshi** [comment]
![hsweb2](https://user-images.githubusercontent.com/3894605/29493190-5cc7bf2a-85c4-11e7-901d-2f5781f8a15e.png)

**Comment by zhou-hao** [comment]
不要被吓到了.  这样看就行 .了
![image](https://user-images.githubusercontent.com/7791838/29500051-639c4a6a-864f-11e7-93c0-83feb282fd81.png)

**Comment by barrycheng** [comment]
@zhou-hao 。。。看是解决了，怎么快速开始开发啊。。。我现在公司闲的一逼，想加入这个项目

**Comment by zhou-hao** [comment]
@barrycheng  你可以加入QQ群:515649185

**Comment by barrycheng** [comment]
@zhou-hao 虽然没事做，但是我们不能上QQ啊。。。哈哈哈
