### ISSUE TITLE
关于这个hsweb-framework-master怎么导入到eclipse上，这种项目结构没用过

### ISSUE THREAD

**Issue by lihuazhong** [hs-web/hsweb-framework#57]
hsweb-framework-master项目导入eclipse时说导入目录不是项目，这个hsweb下有子目录模块里有pom.xml文件 eclipse应该不会识别出来呀  大佬们是怎么导入和搭建好环境的   我是个新手额外学习新知识希望你们给点鼓励

**Comment by genericyzh** [comment]
推荐使用idea..
