### ISSUE TITLE
demo.hsweb.me 已经 502 了知道吗？

### ISSUE THREAD

**Issue by zhaoming-mike** [hs-web/hsweb-framework#59]
如图

![2](https://user-images.githubusercontent.com/1475727/33199595-e604b6a0-d12b-11e7-8302-5c4f93738b23.png)

**Comment by zhaoming-mike** [comment]
![1](https://user-images.githubusercontent.com/1475727/33199551-ba7bd6a8-d12b-11e7-893c-b11ea601264c.png)

**Comment by zhou-hao** [comment]
前段时间服务器到期。现在已经恢复
