### ISSUE TITLE
有人清楚这个错误是怎么产生的吗？

### ISSUE THREAD

**Issue by sg157** [hs-web/hsweb-framework#60]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.hswebframework.web.tests.SimpleWebApplicationTests$Config]; nested exception is java.io.FileNotFoundException: class path resource [org/apache/ibatis/plugin/Interceptor.class] cannot be opened because it does not exist

**Comment by zhou-hao** [comment]
看上去像依赖包没有下载完整
