### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by 872239537** [hs-web/hsweb-framework#62]
使用simple中的 server和client在AuthenticationHolder中无法获取用户id，用户id是什么时候赋值到threadlocal中的？

**Comment by zhou-hao** [comment]
获取的时候 已经授权了吗？

**Comment by 872239537** [comment]
直接运行smple中的server和client，登录成功后请求oauth认证时无法获取当前用户，需要手动授权么？

**Comment by zhou-hao** [comment]
未能复现你说的问题.
操作步骤:
1. 启动server和client
2. 打开 http://localhost:8808/login.html
3. 点击使用hsweb登录
4. 登录admin ，admin
5. 跳转到原网页，并显示用户信息

**Comment by 872239537** [comment]
谢谢，我使用最新的是好的。有问题的是一个月前的，thinks
