### ISSUE TITLE
HttpTokenRequest 这个类貌似有点问题

### ISSUE THREAD

**Issue by yunweiguo** [hs-web/hsweb-framework#63]
protected ClientCredentials getClientCredentials(String principal, String credentials, String authorization) {
        if ((principal == null || credentials == null) && authorization == null) {
            return null;
        }
        if (authorization != null && !authorization.isEmpty()) {
            String[] decodeCredentials = decodeClientAuthenticationHeader(authorization);
            if (decodeCredentials.length > 1) {
                principal = decodeCredentials[0];
                credentials = decodeCredentials[1];
            } else {
                credentials = decodeCredentials[0];
            }
        }
        return new ClientCredentials(principal, credentials);
    }

    protected String[] decodeClientAuthenticationHeader(String authenticationHeader) {
        if (StringUtils.isNullOrEmpty(authenticationHeader)) {
            return null;
        } else {
            String[] tokens = authenticationHeader.split(" ");
            if (tokens.length != 2) {
                return null;
            } else {
                String authType = tokens[0];
                if (!"basic".equalsIgnoreCase(authType)) {
                    return ErrorType.OTHER.throwThis(GrantTokenException::new, "authentication " + authType + " not support!");
                } else {
                    String encodedCreds = tokens[1];
                    return decodeBase64EncodedCredentials(encodedCreds);
                }
            }
        }
    }

我的问题是 
 if (authorization != null && !authorization.isEmpty()) {
            String[] decodeCredentials = decodeClientAuthenticationHeader(authorization);
            if (decodeCredentials.length > 1) {
                principal = decodeCredentials[0];
                credentials = decodeCredentials[1];
            } else {
                credentials = decodeCredentials[0];
            }
这段代码中，如果decodeClientAuthenticationHeader函数获取到的结果为null，那么获取decodeCredentials[0]不是会有问题吗？

**Comment by vigorous** [comment]
这个不可能为空的吧



quick_to_bowl@163.com
 
发件人： Weiguo Yun
发送时间： 2018-01-04 11:21
收件人： hs-web/hsweb-framework
抄送： Subscribed
主题： [hs-web/hsweb-framework] HttpTokenRequest 这个类貌似有点问题 (#63)
protected ClientCredentials getClientCredentials(String principal, String credentials, String authorization) {
if ((principal == null || credentials == null) && authorization == null) {
return null;
}
if (authorization != null && !authorization.isEmpty()) {
String[] decodeCredentials = decodeClientAuthenticationHeader(authorization);
if (decodeCredentials.length > 1) {
principal = decodeCredentials[0];
credentials = decodeCredentials[1];
} else {
credentials = decodeCredentials[0];
}
}
return new ClientCredentials(principal, credentials);
}
protected String[] decodeClientAuthenticationHeader(String authenticationHeader) {
    if (StringUtils.isNullOrEmpty(authenticationHeader)) {
        return null;
    } else {
        String[] tokens = authenticationHeader.split(" ");
        if (tokens.length != 2) {
            return null;
        } else {
            String authType = tokens[0];
            if (!"basic".equalsIgnoreCase(authType)) {
                return ErrorType.OTHER.throwThis(GrantTokenException::new, "authentication " + authType + " not support!");
            } else {
                String encodedCreds = tokens[1];
                return decodeBase64EncodedCredentials(encodedCreds);
            }
        }
    }
}

我的问题是
if (authorization != null && !authorization.isEmpty()) {
String[] decodeCredentials = decodeClientAuthenticationHeader(authorization);
if (decodeCredentials.length > 1) {
principal = decodeCredentials[0];
credentials = decodeCredentials[1];
} else {
credentials = decodeCredentials[0];
}
这段代码中，如果decodeClientAuthenticationHeader函数获取到的结果为null，那么获取decodeCredentials[0]不是会有问题吗？

**Comment by yunweiguo** [comment]
String[] tokens = authenticationHeader.split(" ");
if (tokens.length != 2) {
    return null;
如果tokens的长度不是为2的话，那么此时返回的是 空。或者说tokens的长度一定会是2？

**Comment by zhou-hao** [comment]
@yunweiguo 这个严格来说 算是bug。

**Comment by zhou-hao** [comment]
https://github.com/hs-web/hsweb-framework/blob/cae41cc0aa39c1eae28fb08a03b6dc21e5912610/hsweb-authorization/hsweb-authorization-oauth2/hsweb-authorization-oauth2-auth-server/src/main/java/org/hswebframework/web/authorization/oauth2/server/support/HttpTokenRequest.java#L79-L97

**Comment by vigorous** [comment]
为什么会选择layui，其他的开源的ui不选呢？



quick_to_bowl@163.com
 
发件人： zhōuhào
发送时间： 2018-01-16 22:58
收件人： hs-web/hsweb-framework
抄送： vigorous; Comment
主题： Re: [hs-web/hsweb-framework] HttpTokenRequest 这个类貌似有点问题 (#63)
Closed #63.

**Comment by zhou-hao** [comment]
@vigorous 1. layui 开源，2. 上手简单 3. 样式还不错

**Comment by vigorous** [comment]
开源很重要，有完整的API，样式有点小清新。
看了一下，一些图表模板没有，一般用都没什么问题。

发送自 Windows 10 版邮件应用

发件人: zhōuhào
发送时间: 2018年1月17日 15:41
收件人: hs-web/hsweb-framework
抄送: vigorous; Mention
主题: Re: [hs-web/hsweb-framework] HttpTokenRequest 这个类貌似有点问题 (#63)

@vigorous 1. layui 开源，2. 上手简单 3. 样式还不错
