### ISSUE TITLE
欢迎使用hsweb

### ISSUE THREAD

**Issue by zhou-hao** [hs-web/hsweb-framework#64]
hsweb发展已经近2年,即将推出pro版,此版本依然将开源下去,后期将提供付费模式帮助`hsweb`更好的发展.
-  ~全新的ui,使用layui作为新的ui框架,并对其封装~ (layui不太适用,放弃之)
-  全新的表单设计器,可拖拽设计表单
- 多种权限设置方式
- 更多的模板项目

更多想要的功能,特性? `comment` 吧. 我会酌情加入到hsweb中

**Comment by ying-bin** [comment]
赞👍

**Comment by crazyrunsnail** [comment]
1

**Comment by changdaye** [comment]
买断了 多少钱。

**Comment by one-next** [comment]
不容易终于走向赚钱了。。

**Comment by Mr-Felixu** [comment]
买断了 多少钱。

**Comment by lengjiaxin** [comment]
好神威武

**Comment by sendya** [comment]
:no_mouth:

**Comment by chen834229260** [comment]
赞

**Comment by gmle** [comment]
买断 多少钱

**Comment by longfeizheng** [comment]
👍

**Comment by lvmingliang** [comment]
加油！

**Comment by kangfoo** [comment]
怎么卖的呢？

**Comment by downlder** [comment]
楼主多大了，这是我至今见过最牛逼的国人框架（还有一个叫啥tiny也不错)，一己之力开发的？

**Comment by changdaye** [comment]
@downlder  00 后。

**Comment by downlder** [comment]
我觉得10年以上才有这种功力

**Comment by kleen** [comment]
layui 也不合适做 后台管理的项目吧

**Comment by zhou-hao** [comment]
@downlder 5年。  使用的时候并不是把整个 hsweb-framework 扒下来改。 而是需要啥。通过maven去依赖。实际使用的时候。是没有这么细的。

**Comment by kleen** [comment]
@zhou-hao  我觉得，你可以与miniui那边沟通的，他们之前是找 jeesite 那套东西来谈合作！ 我是他们会员，如需要可以然他们给你免费授权的， 你也是算给他们推广产品呀

**Comment by techzealot** [comment]
@zhou-hao 有没有考虑过前后端完全分离？推荐iview-admin 或者 ant design pro

**Comment by zhou-hao** [comment]
@techzealot 现在就是完全分离的哦。只是前端我没怎么搞。

**Comment by Gaea-IT** [comment]
私服 不行啊，太慢了

**Comment by downlder** [comment]
哥们，分得这么细，会不会过度设计了啊

**Comment by vito16** [comment]
就是感觉document这一块现在做的不好。入门使用有难度的。

**Comment by xlzuijia** [comment]
大佬建个qq群或者微信群   交流下啊

**Comment by xlzuijia** [comment]
刚接触 这个项目 很多不懂

**Comment by lengjiaxin** [comment]
515649185
