### ISSUE TITLE
这个日记解析的为什么会是findAny 

### ISSUE THREAD

**Issue by kleen** [hs-web/hsweb-framework#66]
我看代码有注入两个
DefaultAccessLoggerParser.java
SwaggerAccessLoggerParser.java

debug下来实际只有 SwaggerAccessLoggerParser
![image](https://user-images.githubusercontent.com/3284413/37238519-ed54fcbe-2462-11e8-98de-85ae8408501e.png)

**Comment by zhou-hao** [comment]
优先使用swagger。  因为swagger是后来加入的。为了兼容以前的用法。所以提供了2个parser。
