### ISSUE TITLE
ezorm和util的代码能否公开，学习一下

### ISSUE THREAD

**Issue by Jerome-Kwok** [hs-web/hsweb-framework#69]
这几天在github上溜达，看到这个项目，感觉框架不错，检出来发现有几个内部功能模块是没有代码的，以jar包的形式提供依赖，布置能否给共享一下，学习整体框架。多谢！
以下这三处的代码没有找到，不知是我是我的遗漏，没找到地方：
        <hsweb.ezorm.version>3.0.1-SNAPSHOT</hsweb.ezorm.version>
        <hsweb.utils.version>3.0.2</hsweb.utils.version>
        <hsweb.expands.version>3.0.2-SNAPSHOT</hsweb.expands.version>

**Comment by zhou-hao** [comment]
都是开源的。 不过这几个模板比较老了。是2.0的产物。写的并不是很好
  https://github.com/hs-web/hsweb-easy-orm  

 https://github.com/hs-web/hsweb-expands  

https://github.com/hs-web/hsweb-utils

**Comment by Jerome-Kwok** [comment]
嗯，非常感谢，学习一下，这几个模块可以整合到hsweb-framework这个框架里吗，还是必须单独打包做引用。

**Comment by Jerome-Kwok** [comment]
那就是说我们这个框架的orm框架用的事2.0的？没有使用MyBatis做为持久层吗

**Comment by zhou-hao** [comment]
这几个工具都是2.0的时候写的。所以代码质量一般，但是3.0在继续使用。orm 现在仍然是mybatis。基于easyorm做的动态条件，你也可以直接写原生的mybatis。  这3个包都已经上传到maven中央仓库了。不需要单独打包的。

**Comment by Jerome-Kwok** [comment]
遇到一个问题，这个工程怎么运行起来呢，不知道部署哪个项目，现在还在排错，能给指点一二吗，文档没有写怎么运行，想在项目组使用这个框架，看来我差的很远，先谢过了！

**Comment by zhou-hao** [comment]
参照 https://github.com/hs-web/hsweb3-demo 运行。 使用hsweb不是直接把framework给扒下来。而是使用maven去依赖想要的模块

**Comment by Jerome-Kwok** [comment]
嗯，好的，多谢！我先研究研究
