### ISSUE TITLE
这个框架是否可以用于公司内部基础框架使用？会涉及到侵权嘛？

### ISSUE THREAD

**Issue by wfm0105** [hs-web/hsweb-framework#72]

**Comment by zhou-hao** [comment]
除了hsweb3-demo中的miniui。 其他你都可以放心的使用。遵循apache2.0协议即可。

**Comment by wfm0105** [comment]
请教下在框架中hsweb.web.mappings.authorize:authorize 这个在哪里配置的？

**Comment by zhou-hao** [comment]
@wfm0105 这个是spel表达式。 从spring配置中获取`hsweb.web.mappings.authorize`配置，如果没有则使用`authorize`作为默认值。  可以查看spring的`Environment`接口。 在spring-boot中,配置可通过环境变量,启动参数,application.yml进行配置。
