### ISSUE TITLE
有没有一个二次开发的guide，我想在这些模块上进行二次开发

### ISSUE THREAD

**Issue by Cain1127** [hs-web/hsweb-framework#80]
1. 问题描述: 有没有一个二次开发的guide，我想在这些模块上进行二次开发

**Comment by zhou-hao** [comment]
你可参照[demo3](https://github.com/hs-web/hsweb3-demo)进行使用。 不推荐直接修改hsweb-framework

**Comment by nivance** [comment]
@zhou-hao demo3不详细，参考demo3加了个表，一直不成功

**Comment by zhou-hao** [comment]
@nivance https://github.com/hs-web/hsweb-framework/tree/master/quick-start
