### ISSUE TITLE
用户登录认证过程存在风险

### ISSUE THREAD

**Issue by JiaRG** [hs-web/hsweb-framework#89]
1. 问题描述: 
     ​    如果用户名提交的是 “” 空字符串，最终解析出来的SQL是  select  xxx from from s_user
2. 复现步骤: 
- 提交用户名为空字符串的情况：

![image](https://user-images.githubusercontent.com/31472350/46661271-7118bd80-cbeb-11e8-8b4f-9f1a20cbe91a.png)
![image](https://user-images.githubusercontent.com/31472350/46661233-5c3c2a00-cbeb-11e8-836c-7b1e02b88f4d.png)
``` SQL
==>  Preparing: select s_user.`u_id` AS `u_id`,s_user.`name` AS `name`,s_user.`username` AS `username`,s_user.`password` AS `password`,s_user.`salt` AS `salt`,s_user.`status` AS `status`,s_user.`create_time` AS `create_time`,s_user.`creator_id` AS `creator_id` from s_user limit 0,1
==> Parameters: 
<==      Total: 1
```

**Comment by zhou-hao** [comment]
感谢提交,此问题是由于orm的动态条件策略是会忽略null和空字符串导致的。将在下一个版本进行修复。

**Comment by zhou-hao** [comment]
已修复,将在3.0.1版本中发布,  [查看测试]( https://github.com/hs-web/hsweb-framework/blob/27e7260bd5f23b9ee3ad40d774f34b7a5b4609c5/hsweb-system/hsweb-system-authorization/hsweb-system-authorization-starter/src/test/groovy/org/hswebframework/web/authorization/starter/FixBug89Test.groovy)
3.0.1之前的版本可以通过定义一个`listener`监听事件`AuthorizationDecodeEvent`进行修复:

```java
@EventListener
public void fixBug89(AuthorizationDecodeEvent event){
    Assert.hasLength(event.getUsername(), "用户名不能为空"); 
    Assert.hasLength(event.getPassword(), "密码不能为空");
}
```
