### ISSUE TITLE
常见问题及解决方式

### ISSUE THREAD

**Issue by zhou-hao** [hs-web/hsweb-framework#97]
# 使用hsweb时的常见问题及解决方式
这里只列出了常见问题的解决方式,如果有更多问题,请在下方`留言`或者[提交issues](https://github.com/hs-web/hsweb-framework/issues/new)

##  mybatis报错1
 `There is no getter for property named 'xxxx' in 'class org.hswebframework.web.commons.entity.param.QueryParamEntity'`

检查 Mapper.xml中的配置项:
```xml
 <sql id="config">
 <!--
注意: value值是ognl表达式,因此要使用单引号来声明字符串,例如: 's_organization' 
-->
        <bind name="resultMapId" value="'OrganizationalResultMap'"/>
        <bind name="tableName" value="'s_organization'"/> 
  </sql>
```
## mybatis报错2: 
Invalid bound statement (not found): com.xxxx.Xxxxx.select

1. 检查`Mapper.xml`是否被编译到`target`. 建议将xml都放到`src/resources`目录下
2. 检查`Mapper.xml`所在的包名, 在文件系统里是否为`com/xxx/Xxxx.xml` 而不是 `com.xxx/Xxxx.xml`
3. 检查`application.yml`中是否配置了`mybaits.mapper-locations` 配置,例如:
```yaml
mybatis:
    mapper-locations: com/xxx/**/*.xml

**Comment by SERE026** [comment]
比较垃圾，写得比较多，没什么卵用

**Comment by 22996963** [comment]
您好，跑单元测试，新增一个用户，为何同一个方法会调用两次？
如:  org.hswebframework.web.authorization.Authentication.UserTests createTestUser()

**Comment by zhou-hao** [comment]
@22996963 提供一下具体的代码

**Comment by 22996963** [comment]
@zhou-hao  hsweb-framework 3.0.8-release版本。  数据库 mysql,
跑 UserTests testAddUser()方法。

![image](https://user-images.githubusercontent.com/13128026/61453687-69175680-a991-11e9-985b-1c3d0afa3458.png)

日志如下:
![image](https://user-images.githubusercontent.com/13128026/61453781-a4198a00-a991-11e9-9604-5992e104f2ac.png)

**Comment by 22996963** [comment]
@zhou-hao 解决了，测试代码的问题。

**Comment by kongqiu** [comment]
您好，  hsweb用户手册 - 增删改查 - 通用CRUD - Mybatis/TestMapper.xml 这个文件里的              
` <include refid="BasicMapper.buildInsertSql"/> ` 
 refid在前面没有定义啊，在测试的时候报错:
_{"message":"Could not find SQL statement to include with refid 'BasicMapper.buildInsertSql'","status":500,"timestamp":1578578895439}_

**Comment by zhou-hao** [comment]
引入hsweb-commons-mybatis没

**Comment by kongqiu** [comment]
@zhou-hao  引入了，还是报同样的错。
```
             <dependency>
                <groupId>org.hswebframework.web</groupId>
                <artifactId>hsweb-commons-mybatis</artifactId>
                <version>${hsweb.framework.version}</version>
            </dependency>
```

**Comment by zhou-hao** [comment]
@kongqiu 你用这个例子看会不会报错  https://github.com/hs-web/hsweb-examples/tree/master/myproject

**Comment by kongqiu** [comment]
@zhou-hao  解决了，谢谢。把pom.xml里的东西拷贝到我的项目里重新导入依赖包后没问题了，还是依赖的问题。

**Comment by sunguoji** [comment]
not in没有空格
