### ISSUE TITLE
MapperScan注解报错

### ISSUE THREAD

**Issue by yy598162719** [hs-web/hsweb-framework#99]
1. 问题描述:MapperScan注解红色，报错，3.2.0版本，照着快速开始里面的步骤做的，可是这个注解的包并没有添加，安装然后添加依赖，完成了所有步骤(dao.service.controller)之后只有这个地方报错。
2. 复现步骤:MapperScan注解红色
3. 日志内容:MapperScan注解红色

**Comment by zhou-hao** [comment]
1. 当前的版本为 `3.0.2`,你说的`3.2.0`?
2. 检查是否引入了包:  `import org.mybatis.spring.annotation.MapperScan;`
3. 检查依赖是否正确下载:
```
        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-commons-dao-mybatis</artifactId>
            <version>${hsweb.framework.version}</version>
        </dependency>
```

**Comment by yy598162719** [comment]
感觉是hsweb-commons-dao-mybatis没有正确下载，但是明明安装完全部依赖没有报错，也能在test项目点进去这个依赖，就是没有正确导入这个包，我也不知道为何，很郁闷

**Comment by zhou-hao** [comment]
删除本地maven仓库的`org/hswebframework/web` 目录. 然后重新reimport一下maven试试. 如果还不行,试试使用maven命令`mvn clean compile` 看是否报错。

**Comment by yy598162719** [comment]
试过compile和重新install还是没有把那个包导进来，可能是我机器的问题吧。 
最后自己在test项目添加了三个依赖之后项目暂时成功启动了
  <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-spring</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.2</version>
        </dependency>
如果大神有更好的建议还请告诉我

**Comment by yy598162719** [comment]
哇，运行测试的时候还是出现问题，BasicMapper.buildInsertSql出错，还是因为hsweb-commons-dao-mybatis没有正确添加依赖，可是找不到原因在哪=-=，安装编译都没报错，蛋疼

**Comment by yy598162719** [comment]
最后解决了，原来是<dependencyManagement>里面的所有依赖都没有添加成功。。。
